# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aanout/Documents/mestrado/project_test/project_test/project_test.srcs/sources_1/bd/design_2/ip/design_2_ps7_0/design_2_ps7_0.xci
# IP: The module: 'design_2_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aanout/Documents/mestrado/project_test/project_test/project_test.gen/sources_1/bd/design_2/ip/design_2_ps7_0/design_2_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/aanout/Documents/mestrado/project_test/project_test/project_test.srcs/sources_1/bd/design_2/ip/design_2_ps7_0/design_2_ps7_0.xci
# IP: The module: 'design_2_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aanout/Documents/mestrado/project_test/project_test/project_test.gen/sources_1/bd/design_2/ip/design_2_ps7_0/design_2_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
