# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/aanout/Documents/mestrado/facedetect_fpga_project/vivado/Zedboard-Master.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0/design_2_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_0 || ORIG_REF_NAME==design_2_ps7_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_detectFaces_0_0/design_2_detectFaces_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_detectFaces_0_0 || ORIG_REF_NAME==design_2_detectFaces_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_50M_0/design_2_rst_ps7_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_50M_0 || ORIG_REF_NAME==design_2_rst_ps7_50M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_3_0/design_2_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_3_0 || ORIG_REF_NAME==design_2_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_axi_periph_upgraded_ipi_imp_xbar_0/design_2_ps7_axi_periph_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_axi_periph_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_2_ps7_axi_periph_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_axi_periph_0/design_2_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_4_0/design_2_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_4_0 || ORIG_REF_NAME==design_2_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_5_0/design_2_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_5_0 || ORIG_REF_NAME==design_2_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_6_0/design_2_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_6_0 || ORIG_REF_NAME==design_2_axi_gpio_6_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_7_0/design_2_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_7_0 || ORIG_REF_NAME==design_2_axi_gpio_7_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_8_0/design_2_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_8_0 || ORIG_REF_NAME==design_2_axi_gpio_8_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_9_0/design_2_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_9_0 || ORIG_REF_NAME==design_2_axi_gpio_9_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_10_0/design_2_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_10_0 || ORIG_REF_NAME==design_2_axi_gpio_10_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_11_0/design_2_axi_gpio_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_11_0 || ORIG_REF_NAME==design_2_axi_gpio_11_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_12_0/design_2_axi_gpio_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_12_0 || ORIG_REF_NAME==design_2_axi_gpio_12_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_1_0/design_2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_1_0 || ORIG_REF_NAME==design_2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0/design_2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_axi_periph_imp_auto_pc_0/design_2_ps7_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==design_2_ps7_axi_periph_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/aanout/Documents/mestrado/project_test/project_test/project_test.gen/sources_1/bd/design_2/design_2_ooc.xdc
