// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="detectFaces_detectFaces,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=3250,HLS_SYN_DSP=0,HLS_SYN_FF=6984,HLS_SYN_LUT=14582,HLS_VERSION=2024_2}" *)

module detectFaces (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inData_address0,
        inData_ce0,
        inData_q0,
        result_x_address0,
        result_x_ce0,
        result_x_we0,
        result_x_d0,
        result_y_address0,
        result_y_ce0,
        result_y_we0,
        result_y_d0,
        result_w_address0,
        result_w_ce0,
        result_w_we0,
        result_w_d0,
        result_h_address0,
        result_h_ce0,
        result_h_we0,
        result_h_d0,
        result_size,
        result_size_ap_vld
);

parameter    ap_ST_fsm_state1 = 59'd1;
parameter    ap_ST_fsm_state2 = 59'd2;
parameter    ap_ST_fsm_state3 = 59'd4;
parameter    ap_ST_fsm_state4 = 59'd8;
parameter    ap_ST_fsm_state5 = 59'd16;
parameter    ap_ST_fsm_state6 = 59'd32;
parameter    ap_ST_fsm_state7 = 59'd64;
parameter    ap_ST_fsm_state8 = 59'd128;
parameter    ap_ST_fsm_state9 = 59'd256;
parameter    ap_ST_fsm_state10 = 59'd512;
parameter    ap_ST_fsm_state11 = 59'd1024;
parameter    ap_ST_fsm_state12 = 59'd2048;
parameter    ap_ST_fsm_state13 = 59'd4096;
parameter    ap_ST_fsm_state14 = 59'd8192;
parameter    ap_ST_fsm_state15 = 59'd16384;
parameter    ap_ST_fsm_state16 = 59'd32768;
parameter    ap_ST_fsm_state17 = 59'd65536;
parameter    ap_ST_fsm_state18 = 59'd131072;
parameter    ap_ST_fsm_state19 = 59'd262144;
parameter    ap_ST_fsm_state20 = 59'd524288;
parameter    ap_ST_fsm_state21 = 59'd1048576;
parameter    ap_ST_fsm_state22 = 59'd2097152;
parameter    ap_ST_fsm_state23 = 59'd4194304;
parameter    ap_ST_fsm_state24 = 59'd8388608;
parameter    ap_ST_fsm_state25 = 59'd16777216;
parameter    ap_ST_fsm_state26 = 59'd33554432;
parameter    ap_ST_fsm_state27 = 59'd67108864;
parameter    ap_ST_fsm_state28 = 59'd134217728;
parameter    ap_ST_fsm_state29 = 59'd268435456;
parameter    ap_ST_fsm_state30 = 59'd536870912;
parameter    ap_ST_fsm_state31 = 59'd1073741824;
parameter    ap_ST_fsm_state32 = 59'd2147483648;
parameter    ap_ST_fsm_state33 = 59'd4294967296;
parameter    ap_ST_fsm_state34 = 59'd8589934592;
parameter    ap_ST_fsm_state35 = 59'd17179869184;
parameter    ap_ST_fsm_state36 = 59'd34359738368;
parameter    ap_ST_fsm_state37 = 59'd68719476736;
parameter    ap_ST_fsm_state38 = 59'd137438953472;
parameter    ap_ST_fsm_state39 = 59'd274877906944;
parameter    ap_ST_fsm_state40 = 59'd549755813888;
parameter    ap_ST_fsm_state41 = 59'd1099511627776;
parameter    ap_ST_fsm_state42 = 59'd2199023255552;
parameter    ap_ST_fsm_state43 = 59'd4398046511104;
parameter    ap_ST_fsm_state44 = 59'd8796093022208;
parameter    ap_ST_fsm_state45 = 59'd17592186044416;
parameter    ap_ST_fsm_state46 = 59'd35184372088832;
parameter    ap_ST_fsm_state47 = 59'd70368744177664;
parameter    ap_ST_fsm_state48 = 59'd140737488355328;
parameter    ap_ST_fsm_state49 = 59'd281474976710656;
parameter    ap_ST_fsm_state50 = 59'd562949953421312;
parameter    ap_ST_fsm_state51 = 59'd1125899906842624;
parameter    ap_ST_fsm_state52 = 59'd2251799813685248;
parameter    ap_ST_fsm_state53 = 59'd4503599627370496;
parameter    ap_ST_fsm_state54 = 59'd9007199254740992;
parameter    ap_ST_fsm_state55 = 59'd18014398509481984;
parameter    ap_ST_fsm_state56 = 59'd36028797018963968;
parameter    ap_ST_fsm_state57 = 59'd72057594037927936;
parameter    ap_ST_fsm_state58 = 59'd144115188075855872;
parameter    ap_ST_fsm_state59 = 59'd288230376151711744;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] inData_address0;
output   inData_ce0;
input  [7:0] inData_q0;
output  [6:0] result_x_address0;
output   result_x_ce0;
output   result_x_we0;
output  [31:0] result_x_d0;
output  [6:0] result_y_address0;
output   result_y_ce0;
output   result_y_we0;
output  [31:0] result_y_d0;
output  [6:0] result_w_address0;
output   result_w_ce0;
output   result_w_we0;
output  [31:0] result_w_d0;
output  [6:0] result_h_address0;
output   result_h_ce0;
output   result_h_we0;
output  [31:0] result_h_d0;
output  [31:0] result_size;
output   result_size_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] result_x_address0;
reg result_x_ce0;
reg result_x_we0;
reg[31:0] result_x_d0;
reg[6:0] result_y_address0;
reg result_y_ce0;
reg result_y_we0;
reg[31:0] result_y_d0;
reg[6:0] result_w_address0;
reg result_w_ce0;
reg result_w_we0;
reg[31:0] result_w_d0;
reg[6:0] result_h_address0;
reg result_h_ce0;
reg result_h_we0;
reg[31:0] result_h_d0;
reg result_size_ap_vld;

(* fsm_encoding = "none" *) reg   [58:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] counter;
reg   [16:0] Data_address0;
reg    Data_ce0;
reg    Data_we0;
wire   [7:0] Data_q0;
wire   [0:0] icmp_ln96_fu_395_p2;
reg   [0:0] icmp_ln96_reg_1049;
wire   [16:0] trunc_ln98_2_fu_431_p1;
reg   [16:0] trunc_ln98_2_reg_1053;
wire   [0:0] icmp_ln101_fu_448_p2;
reg   [0:0] icmp_ln101_reg_1058;
reg   [31:0] factor_2_reg_1076;
wire    ap_CS_fsm_state3;
wire   [31:0] grp_fu_363_p2;
reg   [31:0] dc_2_reg_1082;
wire    ap_CS_fsm_state18;
wire   [31:0] grp_fu_368_p2;
reg   [31:0] dc_3_reg_1088;
reg   [31:0] res_size_Scale_0_load_reg_1094;
wire    ap_CS_fsm_state20;
wire   [22:0] trunc_ln130_fu_485_p1;
reg   [22:0] trunc_ln130_reg_1099;
wire   [22:0] trunc_ln130_1_fu_526_p1;
reg   [22:0] trunc_ln130_1_reg_1104;
reg   [0:0] xs_sign_2_reg_1112;
wire   [0:0] tmp_29_fu_586_p3;
reg   [0:0] tmp_29_reg_1118;
wire   [8:0] select_ln18_4_fu_604_p3;
reg   [8:0] select_ln18_4_reg_1123;
reg   [0:0] xs_sign_3_reg_1128;
reg   [7:0] xs_exp_3_reg_1134;
wire   [31:0] val_2_fu_680_p3;
reg   [31:0] val_2_reg_1140;
wire    ap_CS_fsm_state21;
wire   [0:0] tmp_31_fu_696_p3;
reg   [0:0] tmp_31_reg_1147;
wire   [8:0] select_ln18_6_fu_713_p3;
reg   [8:0] select_ln18_6_reg_1152;
wire   [31:0] val_3_fu_773_p3;
reg   [31:0] val_3_reg_1157;
wire    ap_CS_fsm_state22;
wire   [31:0] grp_fu_357_p2;
reg   [31:0] value_assign_reg_1164;
wire    ap_CS_fsm_state44;
wire   [0:0] icmp_ln61_fu_812_p2;
reg   [0:0] icmp_ln61_reg_1171;
wire    ap_CS_fsm_state45;
wire   [0:0] icmp_ln61_2_fu_818_p2;
reg   [0:0] icmp_ln61_2_reg_1176;
wire   [63:0] grp_fu_373_p1;
reg   [63:0] conv_i_reg_1181;
wire    ap_CS_fsm_state46;
wire   [63:0] select_ln61_fu_834_p3;
reg   [63:0] select_ln61_reg_1186;
wire   [25:0] grp_fu_780_p2;
reg   [25:0] sdiv_ln446_reg_1191;
wire    ap_CS_fsm_state52;
wire   [23:0] grp_fu_785_p2;
reg   [23:0] sdiv_ln447_reg_1196;
wire   [63:0] grp_fu_387_p2;
reg   [63:0] dc_reg_1201;
wire    ap_CS_fsm_state53;
wire   [31:0] result_20_fu_847_p3;
reg   [31:0] result_20_reg_1206;
wire   [31:0] result_21_fu_859_p3;
reg   [31:0] result_21_reg_1212;
wire   [25:0] x_ratio_fu_882_p2;
reg   [25:0] x_ratio_reg_1218;
wire   [23:0] y_ratio_fu_905_p2;
reg   [23:0] y_ratio_reg_1223;
wire   [0:0] tmp_fu_937_p3;
reg   [0:0] tmp_reg_1228;
wire    ap_CS_fsm_state54;
reg   [31:0] tmp_14_reg_1233;
reg   [31:0] tmp_15_reg_1238;
reg   [0:0] xs_sign_reg_1243;
wire   [31:0] result_19_fu_1036_p3;
reg   [31:0] result_19_reg_1248;
wire    ap_CS_fsm_state55;
reg   [6:0] result_x_Scale_address0;
reg    result_x_Scale_ce0;
reg    result_x_Scale_we0;
wire   [31:0] result_x_Scale_q0;
reg   [6:0] result_y_Scale_address0;
reg    result_y_Scale_ce0;
reg    result_y_Scale_we0;
wire   [31:0] result_y_Scale_q0;
reg   [6:0] result_w_Scale_address0;
reg    result_w_Scale_ce0;
reg    result_w_Scale_we0;
wire   [31:0] result_w_Scale_q0;
reg   [6:0] result_h_Scale_address0;
reg    result_h_Scale_ce0;
reg    result_h_Scale_we0;
wire   [31:0] result_h_Scale_q0;
reg   [16:0] IMG1_data_address0;
reg    IMG1_data_ce0;
reg    IMG1_data_we0;
wire   [7:0] IMG1_data_q0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_ready;
wire   [8:0] grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_ce0;
wire   [16:0] grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_we0;
wire   [7:0] grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_d0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_ready;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_d0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_done;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_idle;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_ready;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_d0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_ce0;
wire   [6:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_address0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_ce0;
wire    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_we0;
wire   [31:0] grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_d0;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_done;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_idle;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_ready;
wire   [16:0] grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_address0;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_ce0;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_we0;
wire   [7:0] grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_d0;
wire   [16:0] grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_address0;
wire    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_ce0;
wire    grp_processImage_fu_297_ap_start;
wire    grp_processImage_fu_297_ap_done;
wire    grp_processImage_fu_297_ap_idle;
wire    grp_processImage_fu_297_ap_ready;
wire   [6:0] grp_processImage_fu_297_AllCandidates_x_address0;
wire    grp_processImage_fu_297_AllCandidates_x_ce0;
wire    grp_processImage_fu_297_AllCandidates_x_we0;
wire   [31:0] grp_processImage_fu_297_AllCandidates_x_d0;
wire   [6:0] grp_processImage_fu_297_AllCandidates_y_address0;
wire    grp_processImage_fu_297_AllCandidates_y_ce0;
wire    grp_processImage_fu_297_AllCandidates_y_we0;
wire   [31:0] grp_processImage_fu_297_AllCandidates_y_d0;
wire   [6:0] grp_processImage_fu_297_AllCandidates_w_address0;
wire    grp_processImage_fu_297_AllCandidates_w_ce0;
wire    grp_processImage_fu_297_AllCandidates_w_we0;
wire   [31:0] grp_processImage_fu_297_AllCandidates_w_d0;
wire   [6:0] grp_processImage_fu_297_AllCandidates_h_address0;
wire    grp_processImage_fu_297_AllCandidates_h_ce0;
wire    grp_processImage_fu_297_AllCandidates_h_we0;
wire   [31:0] grp_processImage_fu_297_AllCandidates_h_d0;
wire   [16:0] grp_processImage_fu_297_IMG1_data_address0;
wire    grp_processImage_fu_297_IMG1_data_ce0;
wire   [31:0] grp_processImage_fu_297_ap_return;
wire   [31:0] grp_processImage_fu_297_grp_fu_357_p_din0;
wire   [31:0] grp_processImage_fu_297_grp_fu_357_p_din1;
wire    grp_processImage_fu_297_grp_fu_357_p_ce;
wire   [31:0] grp_processImage_fu_297_grp_fu_373_p_din0;
wire    grp_processImage_fu_297_grp_fu_373_p_ce;
wire   [31:0] grp_processImage_fu_297_grp_fu_376_p_din0;
wire   [31:0] grp_processImage_fu_297_grp_fu_376_p_din1;
wire   [4:0] grp_processImage_fu_297_grp_fu_376_p_opcode;
wire    grp_processImage_fu_297_grp_fu_376_p_ce;
wire   [63:0] grp_processImage_fu_297_grp_fu_387_p_din0;
wire   [63:0] grp_processImage_fu_297_grp_fu_387_p_din1;
wire   [1:0] grp_processImage_fu_297_grp_fu_387_p_opcode;
wire    grp_processImage_fu_297_grp_fu_387_p_ce;
reg   [31:0] storemerge_reg_237;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state58;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg;
reg    ap_block_state2_on_subcall_done;
reg    grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg;
wire   [0:0] and_ln130_fu_554_p2;
reg    grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg;
reg    grp_processImage_fu_297_ap_start_reg;
wire    ap_CS_fsm_state56;
wire   [31:0] add_ln100_fu_436_p2;
reg   [31:0] factor_fu_222;
wire    ap_CS_fsm_state23;
reg   [31:0] res_size_Scale_0_fu_226;
wire    ap_CS_fsm_state59;
reg   [31:0] grp_fu_357_p0;
reg   [31:0] grp_fu_357_p1;
wire    ap_CS_fsm_state41;
reg   [31:0] grp_fu_373_p0;
reg   [31:0] grp_fu_376_p0;
reg   [31:0] grp_fu_376_p1;
wire    ap_CS_fsm_state19;
reg   [63:0] grp_fu_387_p0;
reg   [63:0] grp_fu_387_p1;
wire    ap_CS_fsm_state47;
wire   [26:0] trunc_ln98_fu_401_p1;
wire   [28:0] trunc_ln98_1_fu_413_p1;
wire   [34:0] p_shl_fu_405_p3;
wire   [34:0] p_shl4_fu_417_p3;
wire   [34:0] add_ln98_fu_425_p2;
wire   [31:0] data_2_fu_472_p1;
wire   [7:0] tmp_2_fu_475_p4;
wire   [0:0] icmp_ln130_1_fu_495_p2;
wire   [0:0] icmp_ln130_fu_489_p2;
wire   [0:0] or_ln130_fu_501_p2;
wire   [0:0] grp_fu_376_p2;
wire   [31:0] data_3_fu_513_p1;
wire   [7:0] tmp_4_fu_516_p4;
wire   [0:0] icmp_ln130_3_fu_536_p2;
wire   [0:0] icmp_ln130_2_fu_530_p2;
wire   [0:0] or_ln130_1_fu_542_p2;
wire   [0:0] grp_fu_381_p2;
wire   [0:0] and_ln130_1_fu_507_p2;
wire   [0:0] and_ln130_2_fu_548_p2;
wire   [7:0] xs_exp_2_fu_568_p3;
wire   [8:0] zext_ln317_fu_576_p1;
wire   [8:0] add_ln317_fu_580_p2;
wire   [7:0] sub_ln18_2_fu_594_p2;
wire  signed [8:0] sext_ln18_5_fu_600_p1;
wire   [24:0] mantissa_2_fu_628_p4;
wire  signed [31:0] sext_ln18_6_fu_641_p1;
wire   [78:0] zext_ln15_fu_637_p1;
wire   [78:0] zext_ln18_2_fu_644_p1;
wire   [78:0] lshr_ln18_fu_648_p2;
wire   [78:0] shl_ln18_fu_654_p2;
wire   [31:0] tmp_s_fu_660_p4;
wire   [31:0] tmp_11_fu_670_p4;
wire   [8:0] zext_ln317_1_fu_687_p1;
wire   [8:0] add_ln317_1_fu_690_p2;
wire   [7:0] sub_ln18_3_fu_704_p2;
wire  signed [8:0] sext_ln18_7_fu_709_p1;
wire   [24:0] mantissa_3_fu_721_p4;
wire  signed [31:0] sext_ln18_8_fu_734_p1;
wire   [78:0] zext_ln15_2_fu_730_p1;
wire   [78:0] zext_ln18_3_fu_737_p1;
wire   [78:0] lshr_ln18_2_fu_741_p2;
wire   [78:0] shl_ln18_2_fu_747_p2;
wire   [31:0] tmp_12_fu_753_p4;
wire   [31:0] tmp_13_fu_763_p4;
wire   [26:0] grp_fu_780_p0;
wire   [25:0] grp_fu_785_p0;
wire   [31:0] bitcast_ln61_fu_795_p1;
wire   [7:0] tmp_6_fu_798_p4;
wire   [22:0] trunc_ln61_fu_808_p1;
wire   [0:0] or_ln61_fu_824_p2;
wire   [0:0] and_ln61_fu_828_p2;
wire   [31:0] result_13_fu_842_p2;
wire   [31:0] result_17_fu_854_p2;
wire   [25:0] trunc_ln446_fu_866_p1;
wire   [25:0] sub_ln446_fu_869_p2;
wire   [25:0] select_ln446_fu_875_p3;
wire   [23:0] trunc_ln447_fu_889_p1;
wire   [23:0] sub_ln447_fu_892_p2;
wire   [23:0] select_ln447_fu_898_p3;
wire   [63:0] data_fu_912_p1;
wire   [10:0] xs_exp_fu_915_p3;
wire   [11:0] zext_ln486_fu_927_p1;
wire   [11:0] add_ln486_fu_931_p2;
wire   [10:0] sub_ln18_fu_945_p2;
wire  signed [11:0] sext_ln18_fu_951_p1;
wire   [11:0] select_ln18_fu_955_p3;
wire  signed [31:0] sext_ln18_4_fu_963_p1;
wire   [51:0] trunc_ln505_fu_923_p1;
wire   [53:0] mantissa_fu_971_p4;
wire   [136:0] zext_ln18_4_fu_981_p1;
wire   [136:0] zext_ln18_fu_967_p1;
wire   [136:0] lshr_ln18_3_fu_991_p2;
wire   [136:0] shl_ln18_3_fu_985_p2;
wire   [31:0] val_fu_1025_p3;
wire   [31:0] result_fu_1030_p2;
reg    grp_fu_357_ce;
reg    grp_fu_373_ce;
reg    grp_fu_376_ce;
reg   [4:0] grp_fu_376_opcode;
reg    grp_fu_387_ce;
reg    grp_fu_780_ap_start;
wire    grp_fu_780_ap_done;
reg    grp_fu_785_ap_start;
wire    grp_fu_785_ap_done;
reg   [58:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
reg    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
reg    ap_ST_fsm_state56_blk;
reg    ap_ST_fsm_state57_blk;
reg    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 59'd1;
#0 counter = 32'd0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg = 1'b0;
#0 grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg = 1'b0;
#0 grp_processImage_fu_297_ap_start_reg = 1'b0;
#0 factor_fu_222 = 32'd0;
#0 res_size_Scale_0_fu_226 = 32'd0;
end

detectFaces_Data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
Data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Data_address0),
    .ce0(Data_ce0),
    .we0(Data_we0),
    .d0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_d0),
    .q0(Data_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_x_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_x_Scale_address0),
    .ce0(result_x_Scale_ce0),
    .we0(result_x_Scale_we0),
    .d0(grp_processImage_fu_297_AllCandidates_x_d0),
    .q0(result_x_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_y_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_y_Scale_address0),
    .ce0(result_y_Scale_ce0),
    .we0(result_y_Scale_we0),
    .d0(grp_processImage_fu_297_AllCandidates_y_d0),
    .q0(result_y_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_w_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_w_Scale_address0),
    .ce0(result_w_Scale_ce0),
    .we0(result_w_Scale_we0),
    .d0(grp_processImage_fu_297_AllCandidates_w_d0),
    .q0(result_w_Scale_q0)
);

detectFaces_result_x_Scale_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
result_h_Scale_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_h_Scale_address0),
    .ce0(result_h_Scale_ce0),
    .we0(result_h_Scale_we0),
    .d0(grp_processImage_fu_297_AllCandidates_h_d0),
    .q0(result_h_Scale_q0)
);

detectFaces_IMG1_data_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
IMG1_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(IMG1_data_address0),
    .ce0(IMG1_data_ce0),
    .we0(IMG1_data_we0),
    .d0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_d0),
    .q0(IMG1_data_q0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_97_1 grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_ready),
    .mul_ln98(trunc_ln98_2_reg_1053),
    .inData_address0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_address0),
    .inData_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_ce0),
    .inData_q0(inData_q0),
    .Data_address0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_address0),
    .Data_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_ce0),
    .Data_we0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_we0),
    .Data_d0(grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_d0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_102_2 grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_ready),
    .result_x_address0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_address0),
    .result_x_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_ce0),
    .result_x_we0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_we0),
    .result_x_d0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_d0),
    .result_y_address0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_address0),
    .result_y_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_ce0),
    .result_y_we0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_we0),
    .result_y_d0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_d0),
    .result_w_address0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_address0),
    .result_w_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_ce0),
    .result_w_we0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_we0),
    .result_w_d0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_d0),
    .result_h_address0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_address0),
    .result_h_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_ce0),
    .result_h_we0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_we0),
    .result_h_d0(grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_d0)
);

detectFaces_detectFaces_Pipeline_VITIS_LOOP_166_3 grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start),
    .ap_done(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_ready),
    .result_x_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_address0),
    .result_x_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_ce0),
    .result_x_Scale_q0(result_x_Scale_q0),
    .result_x_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_address0),
    .result_x_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_ce0),
    .result_x_we0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_we0),
    .result_x_d0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_d0),
    .result_y_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_address0),
    .result_y_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_ce0),
    .result_y_Scale_q0(result_y_Scale_q0),
    .result_y_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_address0),
    .result_y_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_ce0),
    .result_y_we0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_we0),
    .result_y_d0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_d0),
    .result_w_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_address0),
    .result_w_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_ce0),
    .result_w_Scale_q0(result_w_Scale_q0),
    .result_w_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_address0),
    .result_w_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_ce0),
    .result_w_we0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_we0),
    .result_w_d0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_d0),
    .result_h_Scale_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_address0),
    .result_h_Scale_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_ce0),
    .result_h_Scale_q0(result_h_Scale_q0),
    .result_h_address0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_address0),
    .result_h_ce0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_ce0),
    .result_h_we0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_we0),
    .result_h_d0(grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_d0)
);

detectFaces_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1 grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start),
    .ap_done(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_done),
    .ap_idle(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_idle),
    .ap_ready(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_ready),
    .result_16(result_21_reg_1212),
    .y_ratio(y_ratio_reg_1223),
    .IMG1_data_address0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_address0),
    .IMG1_data_ce0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_ce0),
    .IMG1_data_we0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_we0),
    .IMG1_data_d0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_d0),
    .result_15(result_20_reg_1206),
    .sext_ln446(x_ratio_reg_1218),
    .Data_address0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_address0),
    .Data_ce0(grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_ce0),
    .Data_q0(Data_q0)
);

detectFaces_processImage grp_processImage_fu_297(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_processImage_fu_297_ap_start),
    .ap_done(grp_processImage_fu_297_ap_done),
    .ap_idle(grp_processImage_fu_297_ap_idle),
    .ap_ready(grp_processImage_fu_297_ap_ready),
    .factor(factor_2_reg_1076),
    .sum_row(result_21_reg_1212),
    .sum_col(result_20_reg_1206),
    .AllCandidates_x_address0(grp_processImage_fu_297_AllCandidates_x_address0),
    .AllCandidates_x_ce0(grp_processImage_fu_297_AllCandidates_x_ce0),
    .AllCandidates_x_we0(grp_processImage_fu_297_AllCandidates_x_we0),
    .AllCandidates_x_d0(grp_processImage_fu_297_AllCandidates_x_d0),
    .AllCandidates_y_address0(grp_processImage_fu_297_AllCandidates_y_address0),
    .AllCandidates_y_ce0(grp_processImage_fu_297_AllCandidates_y_ce0),
    .AllCandidates_y_we0(grp_processImage_fu_297_AllCandidates_y_we0),
    .AllCandidates_y_d0(grp_processImage_fu_297_AllCandidates_y_d0),
    .AllCandidates_w_address0(grp_processImage_fu_297_AllCandidates_w_address0),
    .AllCandidates_w_ce0(grp_processImage_fu_297_AllCandidates_w_ce0),
    .AllCandidates_w_we0(grp_processImage_fu_297_AllCandidates_w_we0),
    .AllCandidates_w_d0(grp_processImage_fu_297_AllCandidates_w_d0),
    .AllCandidates_h_address0(grp_processImage_fu_297_AllCandidates_h_address0),
    .AllCandidates_h_ce0(grp_processImage_fu_297_AllCandidates_h_ce0),
    .AllCandidates_h_we0(grp_processImage_fu_297_AllCandidates_h_we0),
    .AllCandidates_h_d0(grp_processImage_fu_297_AllCandidates_h_d0),
    .AllCandidates_size_read(res_size_Scale_0_fu_226),
    .IMG1_data_address0(grp_processImage_fu_297_IMG1_data_address0),
    .IMG1_data_ce0(grp_processImage_fu_297_IMG1_data_ce0),
    .IMG1_data_q0(IMG1_data_q0),
    .winSize_width(result_19_reg_1248),
    .ap_return(grp_processImage_fu_297_ap_return),
    .grp_fu_357_p_din0(grp_processImage_fu_297_grp_fu_357_p_din0),
    .grp_fu_357_p_din1(grp_processImage_fu_297_grp_fu_357_p_din1),
    .grp_fu_357_p_dout0(grp_fu_357_p2),
    .grp_fu_357_p_ce(grp_processImage_fu_297_grp_fu_357_p_ce),
    .grp_fu_373_p_din0(grp_processImage_fu_297_grp_fu_373_p_din0),
    .grp_fu_373_p_dout0(grp_fu_373_p1),
    .grp_fu_373_p_ce(grp_processImage_fu_297_grp_fu_373_p_ce),
    .grp_fu_376_p_din0(grp_processImage_fu_297_grp_fu_376_p_din0),
    .grp_fu_376_p_din1(grp_processImage_fu_297_grp_fu_376_p_din1),
    .grp_fu_376_p_opcode(grp_processImage_fu_297_grp_fu_376_p_opcode),
    .grp_fu_376_p_dout0(grp_fu_376_p2),
    .grp_fu_376_p_ce(grp_processImage_fu_297_grp_fu_376_p_ce),
    .grp_fu_387_p_din0(grp_processImage_fu_297_grp_fu_387_p_din0),
    .grp_fu_387_p_din1(grp_processImage_fu_297_grp_fu_387_p_din1),
    .grp_fu_387_p_opcode(grp_processImage_fu_297_grp_fu_387_p_opcode),
    .grp_fu_387_p_dout0(grp_fu_387_p2),
    .grp_fu_387_p_ce(grp_processImage_fu_297_grp_fu_387_p_ce)
);

detectFaces_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_357_p0),
    .din1(grp_fu_357_p1),
    .ce(grp_fu_357_ce),
    .dout(grp_fu_357_p2)
);

detectFaces_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1134559232),
    .din1(factor_fu_222),
    .ce(1'b1),
    .dout(grp_fu_363_p2)
);

detectFaces_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1131413504),
    .din1(factor_fu_222),
    .ce(1'b1),
    .dout(grp_fu_368_p2)
);

detectFaces_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_373_p0),
    .ce(grp_fu_373_ce),
    .dout(grp_fu_373_p1)
);

detectFaces_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U101(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_376_p0),
    .din1(grp_fu_376_p1),
    .ce(grp_fu_376_ce),
    .opcode(grp_fu_376_opcode),
    .dout(grp_fu_376_p2)
);

detectFaces_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U102(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(dc_3_reg_1088),
    .din1(32'd1103626240),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_381_p2)
);

detectFaces_dadd_64ns_64ns_64_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_7_full_dsp_1_U103(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .ce(grp_fu_387_ce),
    .dout(grp_fu_387_p2)
);

detectFaces_sdiv_27ns_32ns_26_31_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 26 ))
sdiv_27ns_32ns_26_31_seq_1_U104(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_780_ap_start),
    .done(grp_fu_780_ap_done),
    .din0(grp_fu_780_p0),
    .din1(val_2_reg_1140),
    .ce(1'b1),
    .dout(grp_fu_780_p2)
);

detectFaces_sdiv_26ns_32ns_24_30_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 30 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 24 ))
sdiv_26ns_32ns_24_30_seq_1_U105(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_785_ap_start),
    .done(grp_fu_785_ap_done),
    .din0(grp_fu_785_p0),
    .din1(val_3_reg_1157),
    .ce(1'b1),
    .dout(grp_fu_785_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln101_reg_1058 == 1'd1) & (icmp_ln96_reg_1049 == 1'd1))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd0 == and_ln130_fu_554_p2) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln96_fu_395_p2 == 1'd1))) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state53)) begin
            grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg <= 1'b1;
        end else if ((grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_ready == 1'b1)) begin
            grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_processImage_fu_297_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state55)) begin
            grp_processImage_fu_297_ap_start_reg <= 1'b1;
        end else if ((grp_processImage_fu_297_ap_ready == 1'b1)) begin
            grp_processImage_fu_297_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln101_reg_1058 == 1'd0) | (icmp_ln96_reg_1049 == 1'd0)))) begin
        factor_fu_222 <= 32'd1067030938;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        factor_fu_222 <= grp_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln101_reg_1058 == 1'd0) | (icmp_ln96_reg_1049 == 1'd0)))) begin
        res_size_Scale_0_fu_226 <= 32'd0;
    end else if (((grp_processImage_fu_297_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
        res_size_Scale_0_fu_226 <= grp_processImage_fu_297_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state58))) begin
        storemerge_reg_237 <= 32'd0;
    end else if (((grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
        storemerge_reg_237 <= res_size_Scale_0_load_reg_1094;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        conv_i_reg_1181 <= grp_fu_373_p1;
        select_ln61_reg_1186[63] <= select_ln61_fu_834_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln96_fu_395_p2 == 1'd1))) begin
        counter <= add_ln100_fu_436_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        dc_2_reg_1082 <= grp_fu_363_p2;
        dc_3_reg_1088 <= grp_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        dc_reg_1201 <= grp_fu_387_p2;
        result_20_reg_1206 <= result_20_fu_847_p3;
        result_21_reg_1212 <= result_21_fu_859_p3;
        x_ratio_reg_1218 <= x_ratio_fu_882_p2;
        y_ratio_reg_1223 <= y_ratio_fu_905_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        factor_2_reg_1076 <= factor_fu_222;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln101_reg_1058 <= icmp_ln101_fu_448_p2;
        icmp_ln96_reg_1049 <= icmp_ln96_fu_395_p2;
        trunc_ln98_2_reg_1053[16 : 6] <= trunc_ln98_2_fu_431_p1[16 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        icmp_ln61_2_reg_1176 <= icmp_ln61_2_fu_818_p2;
        icmp_ln61_reg_1171 <= icmp_ln61_fu_812_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        res_size_Scale_0_load_reg_1094 <= res_size_Scale_0_fu_226;
        select_ln18_4_reg_1123 <= select_ln18_4_fu_604_p3;
        tmp_29_reg_1118 <= add_ln317_fu_580_p2[32'd8];
        trunc_ln130_1_reg_1104 <= trunc_ln130_1_fu_526_p1;
        trunc_ln130_reg_1099 <= trunc_ln130_fu_485_p1;
        xs_exp_3_reg_1134 <= {{data_3_fu_513_p1[30:23]}};
        xs_sign_2_reg_1112 <= data_2_fu_472_p1[32'd31];
        xs_sign_3_reg_1128 <= data_3_fu_513_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        result_19_reg_1248 <= result_19_fu_1036_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        sdiv_ln446_reg_1191 <= grp_fu_780_p2;
        sdiv_ln447_reg_1196 <= grp_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        select_ln18_6_reg_1152 <= select_ln18_6_fu_713_p3;
        tmp_31_reg_1147 <= add_ln317_1_fu_690_p2[32'd8];
        val_2_reg_1140 <= val_2_fu_680_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        tmp_14_reg_1233 <= {{lshr_ln18_3_fu_991_p2[84:53]}};
        tmp_15_reg_1238 <= {{shl_ln18_3_fu_985_p2[84:53]}};
        tmp_reg_1228 <= add_ln486_fu_931_p2[32'd11];
        xs_sign_reg_1243 <= data_fu_912_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        val_3_reg_1157 <= val_3_fu_773_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        value_assign_reg_1164 <= grp_fu_357_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        Data_address0 = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_address0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln96_reg_1049 == 1'd1))) begin
        Data_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_address0;
    end else begin
        Data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        Data_ce0 = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_Data_ce0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln96_reg_1049 == 1'd1))) begin
        Data_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_ce0;
    end else begin
        Data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln96_reg_1049 == 1'd1))) begin
        Data_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_Data_we0;
    end else begin
        Data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        IMG1_data_address0 = grp_processImage_fu_297_IMG1_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        IMG1_data_address0 = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_address0;
    end else begin
        IMG1_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        IMG1_data_ce0 = grp_processImage_fu_297_IMG1_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        IMG1_data_ce0 = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_ce0;
    end else begin
        IMG1_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        IMG1_data_we0 = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_IMG1_data_we0;
    end else begin
        IMG1_data_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

always @ (*) begin
    if ((grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_done == 1'b0)) begin
        ap_ST_fsm_state54_blk = 1'b1;
    end else begin
        ap_ST_fsm_state54_blk = 1'b0;
    end
end

assign ap_ST_fsm_state55_blk = 1'b0;

always @ (*) begin
    if ((grp_processImage_fu_297_ap_done == 1'b0)) begin
        ap_ST_fsm_state56_blk = 1'b1;
    end else begin
        ap_ST_fsm_state56_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_done == 1'b0)) begin
        ap_ST_fsm_state57_blk = 1'b1;
    end else begin
        ap_ST_fsm_state57_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_done == 1'b0)) begin
        ap_ST_fsm_state58_blk = 1'b1;
    end else begin
        ap_ST_fsm_state58_blk = 1'b0;
    end
end

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_357_ce = grp_processImage_fu_297_grp_fu_357_p_ce;
    end else begin
        grp_fu_357_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_357_p0 = grp_processImage_fu_297_grp_fu_357_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_357_p0 = factor_2_reg_1076;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_357_p0 = factor_fu_222;
    end else begin
        grp_fu_357_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_357_p1 = grp_processImage_fu_297_grp_fu_357_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_357_p1 = 32'd1103101952;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_357_p1 = 32'd1067030938;
    end else begin
        grp_fu_357_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_373_ce = grp_processImage_fu_297_grp_fu_373_p_ce;
    end else begin
        grp_fu_373_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_373_p0 = grp_processImage_fu_297_grp_fu_373_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_373_p0 = value_assign_reg_1164;
    end else begin
        grp_fu_373_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_376_ce = grp_processImage_fu_297_grp_fu_376_p_ce;
    end else begin
        grp_fu_376_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_376_opcode = grp_processImage_fu_297_grp_fu_376_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_376_opcode = 5'd3;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_376_opcode = 5'd2;
    end else begin
        grp_fu_376_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_376_p0 = grp_processImage_fu_297_grp_fu_376_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_376_p0 = value_assign_reg_1164;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_376_p0 = dc_2_reg_1082;
    end else begin
        grp_fu_376_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_376_p1 = grp_processImage_fu_297_grp_fu_376_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_376_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_376_p1 = 32'd1103626240;
    end else begin
        grp_fu_376_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_387_ce = grp_processImage_fu_297_grp_fu_387_p_ce;
    end else begin
        grp_fu_387_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_387_p0 = grp_processImage_fu_297_grp_fu_387_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_387_p0 = conv_i_reg_1181;
    end else begin
        grp_fu_387_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        grp_fu_387_p1 = grp_processImage_fu_297_grp_fu_387_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_fu_387_p1 = select_ln61_reg_1186;
    end else begin
        grp_fu_387_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_780_ap_start = 1'b1;
    end else begin
        grp_fu_780_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_785_ap_start = 1'b1;
    end else begin
        grp_fu_785_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_Scale_address0 = grp_processImage_fu_297_AllCandidates_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_address0;
    end else begin
        result_h_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_Scale_ce0 = grp_processImage_fu_297_AllCandidates_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_Scale_ce0;
    end else begin
        result_h_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_h_Scale_we0 = grp_processImage_fu_297_AllCandidates_h_we0;
    end else begin
        result_h_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_h_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_address0;
    end else begin
        result_h_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_h_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_ce0;
    end else begin
        result_h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_d0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_h_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_d0;
    end else begin
        result_h_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_h_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_h_we0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_h_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_h_we0;
    end else begin
        result_h_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        result_size_ap_vld = 1'b1;
    end else begin
        result_size_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_Scale_address0 = grp_processImage_fu_297_AllCandidates_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_address0;
    end else begin
        result_w_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_Scale_ce0 = grp_processImage_fu_297_AllCandidates_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_Scale_ce0;
    end else begin
        result_w_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_w_Scale_we0 = grp_processImage_fu_297_AllCandidates_w_we0;
    end else begin
        result_w_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_address0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_w_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_address0;
    end else begin
        result_w_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_ce0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_w_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_ce0;
    end else begin
        result_w_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_d0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_w_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_d0;
    end else begin
        result_w_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_w_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_w_we0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_w_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_w_we0;
    end else begin
        result_w_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_Scale_address0 = grp_processImage_fu_297_AllCandidates_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_address0;
    end else begin
        result_x_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_Scale_ce0 = grp_processImage_fu_297_AllCandidates_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_Scale_ce0;
    end else begin
        result_x_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_x_Scale_we0 = grp_processImage_fu_297_AllCandidates_x_we0;
    end else begin
        result_x_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_x_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_address0;
    end else begin
        result_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_x_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_ce0;
    end else begin
        result_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_d0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_x_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_d0;
    end else begin
        result_x_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_x_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_x_we0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_x_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_x_we0;
    end else begin
        result_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_Scale_address0 = grp_processImage_fu_297_AllCandidates_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_Scale_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_address0;
    end else begin
        result_y_Scale_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_Scale_ce0 = grp_processImage_fu_297_AllCandidates_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_Scale_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_Scale_ce0;
    end else begin
        result_y_Scale_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        result_y_Scale_we0 = grp_processImage_fu_297_AllCandidates_y_we0;
    end else begin
        result_y_Scale_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_y_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_address0;
    end else begin
        result_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_y_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_ce0;
    end else begin
        result_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_y_d0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_d0;
    end else begin
        result_y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        result_y_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_result_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        result_y_we0 = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_result_y_we0;
    end else begin
        result_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & ((icmp_ln101_reg_1058 == 1'd0) | (icmp_ln96_reg_1049 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln101_reg_1058 == 1'd1) & (icmp_ln96_reg_1049 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'd0 == and_ln130_fu_554_p2) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            if (((grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state54))) begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            if (((grp_processImage_fu_297_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_state57 : begin
            if (((grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state58 : begin
            if (((grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state58))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_436_p2 = (counter + 32'd1);

assign add_ln317_1_fu_690_p2 = ($signed(zext_ln317_1_fu_687_p1) + $signed(9'd385));

assign add_ln317_fu_580_p2 = ($signed(zext_ln317_fu_576_p1) + $signed(9'd385));

assign add_ln486_fu_931_p2 = ($signed(zext_ln486_fu_927_p1) + $signed(12'd3073));

assign add_ln98_fu_425_p2 = (p_shl_fu_405_p3 + p_shl4_fu_417_p3);

assign and_ln130_1_fu_507_p2 = (or_ln130_fu_501_p2 & grp_fu_376_p2);

assign and_ln130_2_fu_548_p2 = (or_ln130_1_fu_542_p2 & grp_fu_381_p2);

assign and_ln130_fu_554_p2 = (and_ln130_2_fu_548_p2 & and_ln130_1_fu_507_p2);

assign and_ln61_fu_828_p2 = (or_ln61_fu_824_p2 & grp_fu_376_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_done == 1'b0) & (icmp_ln96_reg_1049 == 1'd1));
end

assign bitcast_ln61_fu_795_p1 = value_assign_reg_1164;

assign data_2_fu_472_p1 = dc_2_reg_1082;

assign data_3_fu_513_p1 = dc_3_reg_1088;

assign data_fu_912_p1 = dc_reg_1201;

assign grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_102_2_fu_258_ap_start_reg;

assign grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_166_3_fu_270_ap_start_reg;

assign grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_ap_start_reg;

assign grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start = grp_detectFaces_Pipeline_nearestNeighborL1_nearestNeighborL1_1_fu_286_ap_start_reg;

assign grp_fu_780_p0 = 32'd20971520;

assign grp_fu_785_p0 = 32'd15728640;

assign grp_processImage_fu_297_ap_start = grp_processImage_fu_297_ap_start_reg;

assign icmp_ln101_fu_448_p2 = (($signed(add_ln100_fu_436_p2) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign icmp_ln130_1_fu_495_p2 = ((trunc_ln130_fu_485_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln130_2_fu_530_p2 = ((tmp_4_fu_516_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln130_3_fu_536_p2 = ((trunc_ln130_1_fu_526_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_489_p2 = ((tmp_2_fu_475_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_2_fu_818_p2 = ((trunc_ln61_fu_808_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_812_p2 = ((tmp_6_fu_798_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_395_p2 = (($signed(counter) < $signed(32'd240)) ? 1'b1 : 1'b0);

assign inData_address0 = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_address0;

assign inData_ce0 = grp_detectFaces_Pipeline_VITIS_LOOP_97_1_fu_249_inData_ce0;

assign lshr_ln18_2_fu_741_p2 = zext_ln15_2_fu_730_p1 >> zext_ln18_3_fu_737_p1;

assign lshr_ln18_3_fu_991_p2 = zext_ln18_4_fu_981_p1 >> zext_ln18_fu_967_p1;

assign lshr_ln18_fu_648_p2 = zext_ln15_fu_637_p1 >> zext_ln18_2_fu_644_p1;

assign mantissa_2_fu_628_p4 = {{{{1'd1}, {trunc_ln130_reg_1099}}}, {1'd0}};

assign mantissa_3_fu_721_p4 = {{{{1'd1}, {trunc_ln130_1_reg_1104}}}, {1'd0}};

assign mantissa_fu_971_p4 = {{{{1'd1}, {trunc_ln505_fu_923_p1}}}, {1'd0}};

assign or_ln130_1_fu_542_p2 = (icmp_ln130_3_fu_536_p2 | icmp_ln130_2_fu_530_p2);

assign or_ln130_fu_501_p2 = (icmp_ln130_fu_489_p2 | icmp_ln130_1_fu_495_p2);

assign or_ln61_fu_824_p2 = (icmp_ln61_reg_1171 | icmp_ln61_2_reg_1176);

assign p_shl4_fu_417_p3 = {{trunc_ln98_1_fu_413_p1}, {6'd0}};

assign p_shl_fu_405_p3 = {{trunc_ln98_fu_401_p1}, {8'd0}};

assign result_13_fu_842_p2 = (32'd0 - val_2_reg_1140);

assign result_17_fu_854_p2 = (32'd0 - val_3_reg_1157);

assign result_19_fu_1036_p3 = ((xs_sign_reg_1243[0:0] == 1'b1) ? result_fu_1030_p2 : val_fu_1025_p3);

assign result_20_fu_847_p3 = ((xs_sign_2_reg_1112[0:0] == 1'b1) ? result_13_fu_842_p2 : val_2_reg_1140);

assign result_21_fu_859_p3 = ((xs_sign_3_reg_1128[0:0] == 1'b1) ? result_17_fu_854_p2 : val_3_reg_1157);

assign result_fu_1030_p2 = (32'd0 - val_fu_1025_p3);

assign result_size = storemerge_reg_237;

assign select_ln18_4_fu_604_p3 = ((tmp_29_fu_586_p3[0:0] == 1'b1) ? sext_ln18_5_fu_600_p1 : add_ln317_fu_580_p2);

assign select_ln18_6_fu_713_p3 = ((tmp_31_fu_696_p3[0:0] == 1'b1) ? sext_ln18_7_fu_709_p1 : add_ln317_1_fu_690_p2);

assign select_ln18_fu_955_p3 = ((tmp_fu_937_p3[0:0] == 1'b1) ? sext_ln18_fu_951_p1 : add_ln486_fu_931_p2);

assign select_ln446_fu_875_p3 = ((xs_sign_2_reg_1112[0:0] == 1'b1) ? sub_ln446_fu_869_p2 : trunc_ln446_fu_866_p1);

assign select_ln447_fu_898_p3 = ((xs_sign_3_reg_1128[0:0] == 1'b1) ? sub_ln447_fu_892_p2 : trunc_ln447_fu_889_p1);

assign select_ln61_fu_834_p3 = ((and_ln61_fu_828_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign sext_ln18_4_fu_963_p1 = $signed(select_ln18_fu_955_p3);

assign sext_ln18_5_fu_600_p1 = $signed(sub_ln18_2_fu_594_p2);

assign sext_ln18_6_fu_641_p1 = $signed(select_ln18_4_reg_1123);

assign sext_ln18_7_fu_709_p1 = $signed(sub_ln18_3_fu_704_p2);

assign sext_ln18_8_fu_734_p1 = $signed(select_ln18_6_reg_1152);

assign sext_ln18_fu_951_p1 = $signed(sub_ln18_fu_945_p2);

assign shl_ln18_2_fu_747_p2 = zext_ln15_2_fu_730_p1 << zext_ln18_3_fu_737_p1;

assign shl_ln18_3_fu_985_p2 = zext_ln18_4_fu_981_p1 << zext_ln18_fu_967_p1;

assign shl_ln18_fu_654_p2 = zext_ln15_fu_637_p1 << zext_ln18_2_fu_644_p1;

assign sub_ln18_2_fu_594_p2 = (8'd127 - xs_exp_2_fu_568_p3);

assign sub_ln18_3_fu_704_p2 = (8'd127 - xs_exp_3_reg_1134);

assign sub_ln18_fu_945_p2 = (11'd1023 - xs_exp_fu_915_p3);

assign sub_ln446_fu_869_p2 = (26'd0 - trunc_ln446_fu_866_p1);

assign sub_ln447_fu_892_p2 = (24'd0 - trunc_ln447_fu_889_p1);

assign tmp_11_fu_670_p4 = {{shl_ln18_fu_654_p2[55:24]}};

assign tmp_12_fu_753_p4 = {{lshr_ln18_2_fu_741_p2[55:24]}};

assign tmp_13_fu_763_p4 = {{shl_ln18_2_fu_747_p2[55:24]}};

assign tmp_29_fu_586_p3 = add_ln317_fu_580_p2[32'd8];

assign tmp_2_fu_475_p4 = {{data_2_fu_472_p1[30:23]}};

assign tmp_31_fu_696_p3 = add_ln317_1_fu_690_p2[32'd8];

assign tmp_4_fu_516_p4 = {{data_3_fu_513_p1[30:23]}};

assign tmp_6_fu_798_p4 = {{bitcast_ln61_fu_795_p1[30:23]}};

assign tmp_fu_937_p3 = add_ln486_fu_931_p2[32'd11];

assign tmp_s_fu_660_p4 = {{lshr_ln18_fu_648_p2[55:24]}};

assign trunc_ln130_1_fu_526_p1 = data_3_fu_513_p1[22:0];

assign trunc_ln130_fu_485_p1 = data_2_fu_472_p1[22:0];

assign trunc_ln446_fu_866_p1 = sdiv_ln446_reg_1191[25:0];

assign trunc_ln447_fu_889_p1 = sdiv_ln447_reg_1196[23:0];

assign trunc_ln505_fu_923_p1 = data_fu_912_p1[51:0];

assign trunc_ln61_fu_808_p1 = bitcast_ln61_fu_795_p1[22:0];

assign trunc_ln98_1_fu_413_p1 = counter[28:0];

assign trunc_ln98_2_fu_431_p1 = add_ln98_fu_425_p2[16:0];

assign trunc_ln98_fu_401_p1 = counter[26:0];

assign val_2_fu_680_p3 = ((tmp_29_reg_1118[0:0] == 1'b1) ? tmp_s_fu_660_p4 : tmp_11_fu_670_p4);

assign val_3_fu_773_p3 = ((tmp_31_reg_1147[0:0] == 1'b1) ? tmp_12_fu_753_p4 : tmp_13_fu_763_p4);

assign val_fu_1025_p3 = ((tmp_reg_1228[0:0] == 1'b1) ? tmp_14_reg_1233 : tmp_15_reg_1238);

assign x_ratio_fu_882_p2 = (select_ln446_fu_875_p3 + 26'd1);

assign xs_exp_2_fu_568_p3 = {{data_2_fu_472_p1[30:23]}};

assign xs_exp_fu_915_p3 = {{data_fu_912_p1[62:52]}};

assign y_ratio_fu_905_p2 = (select_ln447_fu_898_p3 + 24'd1);

assign zext_ln15_2_fu_730_p1 = mantissa_3_fu_721_p4;

assign zext_ln15_fu_637_p1 = mantissa_2_fu_628_p4;

assign zext_ln18_2_fu_644_p1 = $unsigned(sext_ln18_6_fu_641_p1);

assign zext_ln18_3_fu_737_p1 = $unsigned(sext_ln18_8_fu_734_p1);

assign zext_ln18_4_fu_981_p1 = mantissa_fu_971_p4;

assign zext_ln18_fu_967_p1 = $unsigned(sext_ln18_4_fu_963_p1);

assign zext_ln317_1_fu_687_p1 = xs_exp_3_reg_1134;

assign zext_ln317_fu_576_p1 = xs_exp_2_fu_568_p3;

assign zext_ln486_fu_927_p1 = xs_exp_fu_915_p3;

always @ (posedge ap_clk) begin
    trunc_ln98_2_reg_1053[5:0] <= 6'b000000;
    select_ln61_reg_1186[62:0] <= 63'b011111111100000000000000000000000000000000000000000000000000000;
end

endmodule //detectFaces
