// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module detectFaces_processImage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        factor,
        sum_row,
        sum_col,
        AllCandidates_x_address0,
        AllCandidates_x_ce0,
        AllCandidates_x_we0,
        AllCandidates_x_d0,
        AllCandidates_y_address0,
        AllCandidates_y_ce0,
        AllCandidates_y_we0,
        AllCandidates_y_d0,
        AllCandidates_w_address0,
        AllCandidates_w_ce0,
        AllCandidates_w_we0,
        AllCandidates_w_d0,
        AllCandidates_h_address0,
        AllCandidates_h_ce0,
        AllCandidates_h_we0,
        AllCandidates_h_d0,
        AllCandidates_size_read,
        IMG1_data_address0,
        IMG1_data_ce0,
        IMG1_data_q0,
        winSize_width,
        ap_return,
        grp_fu_357_p_din0,
        grp_fu_357_p_din1,
        grp_fu_357_p_dout0,
        grp_fu_357_p_ce,
        grp_fu_373_p_din0,
        grp_fu_373_p_dout0,
        grp_fu_373_p_ce,
        grp_fu_376_p_din0,
        grp_fu_376_p_din1,
        grp_fu_376_p_opcode,
        grp_fu_376_p_dout0,
        grp_fu_376_p_ce,
        grp_fu_387_p_din0,
        grp_fu_387_p_din1,
        grp_fu_387_p_opcode,
        grp_fu_387_p_dout0,
        grp_fu_387_p_ce
);

parameter    ap_ST_fsm_state1 = 70'd1;
parameter    ap_ST_fsm_state2 = 70'd2;
parameter    ap_ST_fsm_state3 = 70'd4;
parameter    ap_ST_fsm_state4 = 70'd8;
parameter    ap_ST_fsm_state5 = 70'd16;
parameter    ap_ST_fsm_state6 = 70'd32;
parameter    ap_ST_fsm_state7 = 70'd64;
parameter    ap_ST_fsm_state8 = 70'd128;
parameter    ap_ST_fsm_state9 = 70'd256;
parameter    ap_ST_fsm_state10 = 70'd512;
parameter    ap_ST_fsm_state11 = 70'd1024;
parameter    ap_ST_fsm_state12 = 70'd2048;
parameter    ap_ST_fsm_state13 = 70'd4096;
parameter    ap_ST_fsm_state14 = 70'd8192;
parameter    ap_ST_fsm_state15 = 70'd16384;
parameter    ap_ST_fsm_state16 = 70'd32768;
parameter    ap_ST_fsm_state17 = 70'd65536;
parameter    ap_ST_fsm_state18 = 70'd131072;
parameter    ap_ST_fsm_state19 = 70'd262144;
parameter    ap_ST_fsm_state20 = 70'd524288;
parameter    ap_ST_fsm_state21 = 70'd1048576;
parameter    ap_ST_fsm_state22 = 70'd2097152;
parameter    ap_ST_fsm_state23 = 70'd4194304;
parameter    ap_ST_fsm_state24 = 70'd8388608;
parameter    ap_ST_fsm_state25 = 70'd16777216;
parameter    ap_ST_fsm_state26 = 70'd33554432;
parameter    ap_ST_fsm_state27 = 70'd67108864;
parameter    ap_ST_fsm_state28 = 70'd134217728;
parameter    ap_ST_fsm_state29 = 70'd268435456;
parameter    ap_ST_fsm_state30 = 70'd536870912;
parameter    ap_ST_fsm_state31 = 70'd1073741824;
parameter    ap_ST_fsm_state32 = 70'd2147483648;
parameter    ap_ST_fsm_state33 = 70'd4294967296;
parameter    ap_ST_fsm_state34 = 70'd8589934592;
parameter    ap_ST_fsm_state35 = 70'd17179869184;
parameter    ap_ST_fsm_state36 = 70'd34359738368;
parameter    ap_ST_fsm_state37 = 70'd68719476736;
parameter    ap_ST_fsm_state38 = 70'd137438953472;
parameter    ap_ST_fsm_state39 = 70'd274877906944;
parameter    ap_ST_fsm_state40 = 70'd549755813888;
parameter    ap_ST_fsm_state41 = 70'd1099511627776;
parameter    ap_ST_fsm_state42 = 70'd2199023255552;
parameter    ap_ST_fsm_state43 = 70'd4398046511104;
parameter    ap_ST_fsm_state44 = 70'd8796093022208;
parameter    ap_ST_fsm_state45 = 70'd17592186044416;
parameter    ap_ST_fsm_state46 = 70'd35184372088832;
parameter    ap_ST_fsm_state47 = 70'd70368744177664;
parameter    ap_ST_fsm_state48 = 70'd140737488355328;
parameter    ap_ST_fsm_state49 = 70'd281474976710656;
parameter    ap_ST_fsm_state50 = 70'd562949953421312;
parameter    ap_ST_fsm_state51 = 70'd1125899906842624;
parameter    ap_ST_fsm_state52 = 70'd2251799813685248;
parameter    ap_ST_fsm_state53 = 70'd4503599627370496;
parameter    ap_ST_fsm_state54 = 70'd9007199254740992;
parameter    ap_ST_fsm_state55 = 70'd18014398509481984;
parameter    ap_ST_fsm_state56 = 70'd36028797018963968;
parameter    ap_ST_fsm_state57 = 70'd72057594037927936;
parameter    ap_ST_fsm_state58 = 70'd144115188075855872;
parameter    ap_ST_fsm_state59 = 70'd288230376151711744;
parameter    ap_ST_fsm_state60 = 70'd576460752303423488;
parameter    ap_ST_fsm_state61 = 70'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 70'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 70'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 70'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 70'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 70'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 70'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 70'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 70'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 70'd590295810358705651712;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] factor;
input  [31:0] sum_row;
input  [31:0] sum_col;
output  [6:0] AllCandidates_x_address0;
output   AllCandidates_x_ce0;
output   AllCandidates_x_we0;
output  [31:0] AllCandidates_x_d0;
output  [6:0] AllCandidates_y_address0;
output   AllCandidates_y_ce0;
output   AllCandidates_y_we0;
output  [31:0] AllCandidates_y_d0;
output  [6:0] AllCandidates_w_address0;
output   AllCandidates_w_ce0;
output   AllCandidates_w_we0;
output  [31:0] AllCandidates_w_d0;
output  [6:0] AllCandidates_h_address0;
output   AllCandidates_h_ce0;
output   AllCandidates_h_we0;
output  [31:0] AllCandidates_h_d0;
input  [31:0] AllCandidates_size_read;
output  [16:0] IMG1_data_address0;
output   IMG1_data_ce0;
input  [7:0] IMG1_data_q0;
input  [31:0] winSize_width;
output  [31:0] ap_return;
output  [31:0] grp_fu_357_p_din0;
output  [31:0] grp_fu_357_p_din1;
input  [31:0] grp_fu_357_p_dout0;
output   grp_fu_357_p_ce;
output  [31:0] grp_fu_373_p_din0;
input  [63:0] grp_fu_373_p_dout0;
output   grp_fu_373_p_ce;
output  [31:0] grp_fu_376_p_din0;
output  [31:0] grp_fu_376_p_din1;
output  [4:0] grp_fu_376_p_opcode;
input  [0:0] grp_fu_376_p_dout0;
output   grp_fu_376_p_ce;
output  [63:0] grp_fu_387_p_din0;
output  [63:0] grp_fu_387_p_din1;
output  [1:0] grp_fu_387_p_opcode;
input  [63:0] grp_fu_387_p_dout0;
output   grp_fu_387_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [69:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] stages_array_address0;
wire   [7:0] stages_array_q0;
wire   [4:0] stages_thresh_array_address0;
wire   [11:0] stages_thresh_array_q0;
wire   [31:0] grp_fu_540_p1;
reg   [31:0] reg_574;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state55;
reg   [31:0] reg_579;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state59;
reg   [63:0] reg_585;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state61;
wire   [63:0] grp_fu_564_p1;
reg   [63:0] reg_590;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state48;
reg   [30:0] y_1_reg_1479;
wire    ap_CS_fsm_state2;
wire   [16:0] trunc_ln400_2_fu_649_p1;
reg   [16:0] trunc_ln400_2_reg_1487;
wire   [16:0] add_ln409_fu_687_p2;
reg   [16:0] add_ln409_reg_1492;
wire   [31:0] add_fu_698_p2;
reg   [31:0] add_reg_1511;
wire   [31:0] add4_fu_703_p2;
reg   [31:0] add4_reg_1516;
wire   [31:0] zext_ln201_fu_720_p1;
wire    ap_CS_fsm_state5;
wire   [30:0] add_ln201_fu_730_p2;
reg   [30:0] add_ln201_reg_1529;
wire   [16:0] trunc_ln260_2_fu_766_p1;
reg   [16:0] trunc_ln260_2_reg_1534;
wire   [7:0] trunc_ln201_fu_770_p1;
reg   [7:0] trunc_ln201_reg_1540;
wire   [0:0] notlhs_fu_792_p2;
reg   [0:0] notlhs_reg_1546;
wire    ap_CS_fsm_state15;
wire   [0:0] notrhs_fu_798_p2;
reg   [0:0] notrhs_reg_1551;
wire   [63:0] cond_i57_fu_814_p3;
reg   [63:0] cond_i57_reg_1556;
wire   [16:0] add_ln262_1_fu_851_p2;
reg   [16:0] add_ln262_1_reg_1561;
wire    ap_CS_fsm_state23;
wire   [63:0] data_1_fu_857_p1;
reg   [63:0] data_1_reg_1567;
wire   [31:0] zext_ln202_fu_861_p1;
reg   [31:0] zext_ln202_reg_1574;
wire    ap_CS_fsm_state24;
wire   [30:0] add_ln202_fu_870_p2;
reg   [30:0] add_ln202_reg_1582;
wire   [16:0] trunc_ln260_3_fu_876_p1;
reg   [16:0] trunc_ln260_3_reg_1587;
wire   [16:0] add_ln256_fu_880_p2;
reg   [16:0] add_ln256_reg_1594;
wire    ap_CS_fsm_state25;
wire   [63:0] zext_ln262_2_fu_904_p1;
reg   [63:0] zext_ln262_2_reg_1605;
wire   [63:0] zext_ln263_fu_923_p1;
reg   [63:0] zext_ln263_reg_1625;
wire    ap_CS_fsm_state26;
wire   [31:0] sub_ln256_fu_928_p2;
reg   [31:0] sub_ln256_reg_1650;
wire   [31:0] sub_ln261_fu_934_p2;
reg   [31:0] sub_ln261_reg_1655;
reg   [31:0] SUM1_data_load_3_reg_1660;
reg   [31:0] SUM1_data_load_4_reg_1665;
reg   [31:0] SQSUM1_data_load_2_reg_1670;
wire    ap_CS_fsm_state27;
reg   [31:0] SQSUM1_data_load_3_reg_1675;
wire  signed [31:0] mean_fu_944_p2;
reg  signed [31:0] mean_reg_1680;
wire   [31:0] stddev_fu_953_p2;
reg   [31:0] stddev_reg_1686;
wire    ap_CS_fsm_state28;
wire   [31:0] grp_fu_567_p2;
reg   [31:0] mul_ln266_reg_1692;
wire    ap_CS_fsm_state29;
wire   [30:0] trunc_ln237_fu_979_p1;
reg   [30:0] trunc_ln237_reg_1697;
wire    ap_CS_fsm_state30;
wire   [0:0] icmp_ln268_fu_983_p2;
reg   [0:0] icmp_ln268_reg_1702;
wire   [15:0] grp_int_sqrt_fu_474_ap_return;
reg   [15:0] stddev_3_reg_1706;
wire    ap_CS_fsm_state32;
wire   [0:0] icmp_ln282_fu_989_p2;
reg   [0:0] icmp_ln282_reg_1711;
wire    ap_CS_fsm_state34;
wire   [4:0] add_ln282_fu_995_p2;
reg   [4:0] add_ln282_reg_1715;
reg   [0:0] xs_sign_1_reg_1730;
wire   [0:0] tmp_23_fu_1048_p3;
reg   [0:0] tmp_23_reg_1735;
reg   [31:0] tmp_7_reg_1740;
reg   [31:0] tmp_10_reg_1745;
reg   [7:0] stages_array_load_reg_1750;
wire    ap_CS_fsm_state35;
wire   [12:0] haar_counter_3_fu_1118_p2;
reg   [12:0] haar_counter_3_reg_1755;
reg   [11:0] stages_thresh_array_load_reg_1760;
wire   [7:0] add_ln283_fu_1128_p2;
reg   [7:0] add_ln283_reg_1765;
wire    ap_CS_fsm_state36;
wire  signed [31:0] sext_ln344_fu_1134_p1;
wire   [63:0] grp_fu_555_p2;
reg   [63:0] mul277_i_reg_1778;
wire   [0:0] icmp_ln344_fu_1177_p2;
reg   [0:0] icmp_ln344_reg_1784;
wire    ap_CS_fsm_state49;
wire   [0:0] icmp_ln344_1_fu_1183_p2;
reg   [0:0] icmp_ln344_1_reg_1789;
wire   [0:0] icmp_ln344_2_fu_1189_p2;
reg   [0:0] icmp_ln344_2_reg_1794;
wire   [0:0] icmp_ln344_3_fu_1195_p2;
reg   [0:0] icmp_ln344_3_reg_1799;
wire   [31:0] result_7_fu_1232_p3;
reg   [31:0] result_7_reg_1807;
wire    ap_CS_fsm_state51;
wire   [0:0] icmp_ln61_fu_1257_p2;
reg   [0:0] icmp_ln61_reg_1812;
wire    ap_CS_fsm_state60;
wire   [0:0] icmp_ln61_1_fu_1263_p2;
reg   [0:0] icmp_ln61_1_reg_1817;
wire   [63:0] select_ln61_fu_1279_p3;
reg   [63:0] select_ln61_reg_1822;
reg   [63:0] dc_reg_1827;
wire    ap_CS_fsm_state68;
reg   [0:0] xs_sign_reg_1832;
wire    ap_CS_fsm_state69;
wire   [0:0] tmp_21_fu_1334_p3;
reg   [0:0] tmp_21_reg_1837;
reg   [31:0] tmp_5_reg_1842;
reg   [31:0] tmp_6_reg_1847;
reg   [16:0] SUM1_data_address0;
reg    SUM1_data_ce0;
reg    SUM1_data_we0;
wire   [31:0] SUM1_data_q0;
reg   [16:0] SUM1_data_address1;
reg    SUM1_data_ce1;
wire   [31:0] SUM1_data_q1;
reg   [16:0] SUM1_data_address2;
reg    SUM1_data_ce2;
wire   [31:0] SUM1_data_q2;
reg   [16:0] SUM1_data_address3;
reg    SUM1_data_ce3;
wire   [31:0] SUM1_data_q3;
reg    SUM1_data_ce4;
wire   [31:0] SUM1_data_q4;
reg    SUM1_data_ce5;
wire   [31:0] SUM1_data_q5;
reg    SUM1_data_ce6;
wire   [31:0] SUM1_data_q6;
reg    SUM1_data_ce7;
wire   [31:0] SUM1_data_q7;
reg    SUM1_data_ce8;
wire   [31:0] SUM1_data_q8;
reg    SUM1_data_ce9;
wire   [31:0] SUM1_data_q9;
reg    SUM1_data_ce10;
wire   [31:0] SUM1_data_q10;
reg    SUM1_data_ce11;
wire   [31:0] SUM1_data_q11;
reg   [16:0] SQSUM1_data_address0;
reg    SQSUM1_data_ce0;
reg    SQSUM1_data_we0;
wire   [31:0] SQSUM1_data_q0;
reg   [16:0] SQSUM1_data_address1;
reg    SQSUM1_data_ce1;
wire   [31:0] SQSUM1_data_q1;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_done;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_idle;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_ready;
wire   [16:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_address0;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_ce0;
wire   [16:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address0;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce0;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_we0;
wire   [31:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_d0;
wire   [16:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address1;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce1;
wire   [16:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address0;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce0;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_we0;
wire   [31:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_d0;
wire   [16:0] grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address1;
wire    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce1;
wire    grp_int_sqrt_fu_474_ap_start;
wire    grp_int_sqrt_fu_474_ap_done;
wire    grp_int_sqrt_fu_474_ap_idle;
wire    grp_int_sqrt_fu_474_ap_ready;
wire    grp_processImage_Pipeline_Filters_fu_479_ap_start;
wire    grp_processImage_Pipeline_Filters_fu_479_ap_done;
wire    grp_processImage_Pipeline_Filters_fu_479_ap_idle;
wire    grp_processImage_Pipeline_Filters_fu_479_ap_ready;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address0;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce0;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address1;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce1;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address2;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce2;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address3;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce3;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address4;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce4;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address5;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce5;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address6;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce6;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address7;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce7;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address8;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce8;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address9;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce9;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address10;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce10;
wire   [16:0] grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address11;
wire    grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce11;
wire   [31:0] grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out;
wire    grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out_ap_vld;
reg   [30:0] x_reg_404;
wire    ap_CS_fsm_state70;
reg   [15:0] stddev_4_reg_415;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state31;
reg   [4:0] i_reg_427;
wire    ap_CS_fsm_state50;
wire   [0:0] and_ln344_1_fu_1215_p2;
reg   [31:0] stage_sum_reg_438;
reg   [12:0] haar_counter_reg_450;
reg    grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_int_sqrt_fu_474_ap_start_reg;
reg    grp_processImage_Pipeline_Filters_fu_479_ap_start_reg;
wire    ap_CS_fsm_state37;
wire   [63:0] zext_ln260_fu_894_p1;
wire   [63:0] zext_ln261_fu_913_p1;
wire   [63:0] zext_ln282_fu_1001_p1;
wire   [63:0] zext_ln214_fu_1419_p1;
reg   [30:0] y_fu_190;
wire   [30:0] add_ln393_fu_613_p2;
wire   [0:0] icmp_ln393_fu_608_p2;
wire    ap_CS_fsm_state43;
reg   [30:0] pt_y_fu_206;
wire   [0:0] icmp_ln202_fu_865_p2;
reg   [31:0] AllCandidates_size_0_fu_210;
wire   [31:0] add_ln218_fu_1427_p2;
wire   [0:0] icmp_ln201_fu_725_p2;
reg    SQSUM1_data_ce1_local;
reg   [16:0] SQSUM1_data_address1_local;
reg    SQSUM1_data_ce0_local;
reg   [16:0] SQSUM1_data_address0_local;
reg    SUM1_data_ce3_local;
reg    SUM1_data_ce2_local;
reg    SUM1_data_ce1_local;
reg    SUM1_data_ce0_local;
reg    stages_array_ce0_local;
reg    stages_thresh_array_ce0_local;
reg    AllCandidates_x_we0_local;
wire   [31:0] result_fu_1411_p3;
reg    AllCandidates_x_ce0_local;
reg    AllCandidates_y_we0_local;
reg    AllCandidates_y_ce0_local;
reg    AllCandidates_w_we0_local;
reg    AllCandidates_w_ce0_local;
reg    AllCandidates_h_we0_local;
reg    AllCandidates_h_ce0_local;
reg   [31:0] grp_fu_540_p0;
reg   [63:0] grp_fu_551_p1;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state62;
wire    ap_CS_fsm_state42;
reg  signed [31:0] grp_fu_564_p0;
wire   [31:0] zext_ln393_fu_604_p1;
wire   [26:0] trunc_ln400_fu_619_p1;
wire   [28:0] trunc_ln400_1_fu_631_p1;
wire   [34:0] p_shl_fu_623_p3;
wire   [34:0] p_shl1_fu_635_p3;
wire   [34:0] add_ln400_fu_643_p2;
wire   [7:0] trunc_ln393_fu_653_p1;
wire   [7:0] empty_fu_657_p2;
wire   [15:0] tmp_fu_663_p3;
wire   [13:0] tmp_17_fu_675_p3;
wire   [16:0] zext_ln409_fu_671_p1;
wire   [16:0] zext_ln409_1_fu_683_p1;
wire   [26:0] trunc_ln260_fu_736_p1;
wire   [28:0] trunc_ln260_1_fu_748_p1;
wire   [34:0] p_shl2_fu_740_p3;
wire   [34:0] p_shl3_fu_752_p3;
wire   [34:0] add_ln260_1_fu_760_p2;
wire   [31:0] value_assign_1_to_int_fu_774_p1;
wire   [7:0] tmp_1_fu_778_p4;
wire   [22:0] empty_30_fu_788_p1;
wire   [0:0] empty_31_fu_804_p2;
wire   [0:0] empty_32_fu_808_p2;
wire   [7:0] empty_29_fu_822_p2;
wire   [15:0] tmp_18_fu_827_p3;
wire   [13:0] tmp_19_fu_839_p3;
wire   [16:0] zext_ln262_fu_835_p1;
wire   [16:0] zext_ln262_1_fu_847_p1;
wire   [16:0] add_ln260_fu_890_p2;
wire   [16:0] add_ln262_fu_900_p2;
wire   [16:0] add_ln261_fu_909_p2;
wire   [16:0] add_ln263_fu_919_p2;
wire   [31:0] sub_ln262_fu_940_p2;
wire   [31:0] sub_ln257_fu_949_p2;
wire   [31:0] shl_ln265_fu_958_p2;
wire   [31:0] shl_ln265_1_fu_963_p2;
wire   [31:0] stddev_1_fu_968_p2;
wire   [31:0] stddev_2_fu_974_p2;
wire   [51:0] trunc_ln505_1_fu_1021_p1;
wire   [53:0] mantissa_1_fu_1024_p4;
wire   [10:0] xs_exp_1_fu_1014_p3;
wire   [11:0] zext_ln486_1_fu_1038_p1;
wire   [11:0] add_ln486_1_fu_1042_p2;
wire   [10:0] sub_ln18_1_fu_1056_p2;
wire  signed [11:0] sext_ln18_2_fu_1062_p1;
wire   [11:0] select_ln18_2_fu_1066_p3;
wire  signed [31:0] sext_ln18_3_fu_1074_p1;
wire   [136:0] zext_ln15_1_fu_1034_p1;
wire   [136:0] zext_ln18_1_fu_1078_p1;
wire   [136:0] lshr_ln18_1_fu_1082_p2;
wire   [136:0] shl_ln18_1_fu_1088_p2;
wire   [12:0] zext_ln283_fu_1114_p1;
wire   [7:0] empty_33_fu_1124_p1;
wire   [63:0] bitcast_ln344_fu_1142_p1;
wire   [63:0] bitcast_ln344_1_fu_1160_p1;
wire   [10:0] tmp_8_fu_1146_p4;
wire   [51:0] trunc_ln344_fu_1156_p1;
wire   [10:0] tmp_9_fu_1163_p4;
wire   [51:0] trunc_ln344_1_fu_1173_p1;
wire   [0:0] or_ln344_fu_1201_p2;
wire   [0:0] or_ln344_1_fu_1205_p2;
wire   [0:0] and_ln344_fu_1209_p2;
wire   [0:0] grp_fu_560_p2;
wire   [31:0] val_1_fu_1221_p3;
wire   [31:0] result_6_fu_1226_p2;
wire   [31:0] bitcast_ln61_fu_1239_p1;
wire   [7:0] tmp_3_fu_1243_p4;
wire   [22:0] trunc_ln61_fu_1253_p1;
wire   [0:0] or_ln61_fu_1269_p2;
wire   [0:0] and_ln61_fu_1273_p2;
wire   [63:0] data_fu_1287_p1;
wire   [51:0] trunc_ln505_fu_1306_p1;
wire   [53:0] mantissa_fu_1310_p4;
wire   [10:0] xs_exp_fu_1298_p3;
wire   [11:0] zext_ln486_fu_1324_p1;
wire   [11:0] add_ln486_fu_1328_p2;
wire   [10:0] sub_ln18_fu_1342_p2;
wire  signed [11:0] sext_ln18_fu_1348_p1;
wire   [11:0] select_ln18_fu_1352_p3;
wire  signed [31:0] sext_ln18_1_fu_1360_p1;
wire   [136:0] zext_ln15_fu_1320_p1;
wire   [136:0] zext_ln18_fu_1364_p1;
wire   [136:0] lshr_ln18_fu_1368_p2;
wire   [136:0] shl_ln18_fu_1374_p2;
wire   [31:0] val_fu_1400_p3;
wire   [31:0] result_2_fu_1405_p2;
reg    grp_fu_564_ce;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state47;
reg   [69:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 70'd1;
#0 grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg = 1'b0;
#0 grp_int_sqrt_fu_474_ap_start_reg = 1'b0;
#0 grp_processImage_Pipeline_Filters_fu_479_ap_start_reg = 1'b0;
#0 y_fu_190 = 31'd0;
#0 pt_y_fu_206 = 31'd0;
#0 AllCandidates_size_0_fu_210 = 32'd0;
end

detectFaces_processImage_stages_array_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
stages_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(stages_array_address0),
    .ce0(stages_array_ce0_local),
    .q0(stages_array_q0)
);

detectFaces_processImage_stages_thresh_array_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
stages_thresh_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(stages_thresh_array_address0),
    .ce0(stages_thresh_array_ce0_local),
    .q0(stages_thresh_array_q0)
);

detectFaces_processImage_SUM1_data_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
SUM1_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(SUM1_data_address0),
    .ce0(SUM1_data_ce0),
    .we0(SUM1_data_we0),
    .d0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_d0),
    .q0(SUM1_data_q0),
    .address1(SUM1_data_address1),
    .ce1(SUM1_data_ce1),
    .q1(SUM1_data_q1),
    .address2(SUM1_data_address2),
    .ce2(SUM1_data_ce2),
    .q2(SUM1_data_q2),
    .address3(SUM1_data_address3),
    .ce3(SUM1_data_ce3),
    .q3(SUM1_data_q3),
    .address4(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address4),
    .ce4(SUM1_data_ce4),
    .q4(SUM1_data_q4),
    .address5(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address5),
    .ce5(SUM1_data_ce5),
    .q5(SUM1_data_q5),
    .address6(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address6),
    .ce6(SUM1_data_ce6),
    .q6(SUM1_data_q6),
    .address7(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address7),
    .ce7(SUM1_data_ce7),
    .q7(SUM1_data_q7),
    .address8(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address8),
    .ce8(SUM1_data_ce8),
    .q8(SUM1_data_q8),
    .address9(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address9),
    .ce9(SUM1_data_ce9),
    .q9(SUM1_data_q9),
    .address10(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address10),
    .ce10(SUM1_data_ce10),
    .q10(SUM1_data_q10),
    .address11(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address11),
    .ce11(SUM1_data_ce11),
    .q11(SUM1_data_q11)
);

detectFaces_processImage_SQSUM1_data_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 76800 ),
    .AddressWidth( 17 ))
SQSUM1_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(SQSUM1_data_address0),
    .ce0(SQSUM1_data_ce0),
    .we0(SQSUM1_data_we0),
    .d0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_d0),
    .q0(SQSUM1_data_q0),
    .address1(SQSUM1_data_address1),
    .ce1(SQSUM1_data_ce1),
    .q1(SQSUM1_data_q1)
);

detectFaces_processImage_Pipeline_VITIS_LOOP_398_2 grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start),
    .ap_done(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_done),
    .ap_idle(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_idle),
    .ap_ready(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_ready),
    .sum_col(sum_col),
    .mul_ln400(trunc_ln400_2_reg_1487),
    .IMG1_data_address0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_address0),
    .IMG1_data_ce0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_ce0),
    .IMG1_data_q0(IMG1_data_q0),
    .mul_ln409(add_ln409_reg_1492),
    .SUM1_data_address0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address0),
    .SUM1_data_ce0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce0),
    .SUM1_data_we0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_we0),
    .SUM1_data_d0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_d0),
    .SUM1_data_address1(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address1),
    .SUM1_data_ce1(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce1),
    .SUM1_data_q1(SUM1_data_q1),
    .SQSUM1_data_address0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address0),
    .SQSUM1_data_ce0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce0),
    .SQSUM1_data_we0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_we0),
    .SQSUM1_data_d0(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_d0),
    .SQSUM1_data_address1(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address1),
    .SQSUM1_data_ce1(grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce1),
    .SQSUM1_data_q1(SQSUM1_data_q1),
    .y(y_1_reg_1479)
);

detectFaces_int_sqrt grp_int_sqrt_fu_474(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_int_sqrt_fu_474_ap_start),
    .ap_done(grp_int_sqrt_fu_474_ap_done),
    .ap_idle(grp_int_sqrt_fu_474_ap_idle),
    .ap_ready(grp_int_sqrt_fu_474_ap_ready),
    .value_r(trunc_ln237_reg_1697),
    .ap_return(grp_int_sqrt_fu_474_ap_return)
);

detectFaces_processImage_Pipeline_Filters grp_processImage_Pipeline_Filters_fu_479(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_processImage_Pipeline_Filters_fu_479_ap_start),
    .ap_done(grp_processImage_Pipeline_Filters_fu_479_ap_done),
    .ap_idle(grp_processImage_Pipeline_Filters_fu_479_ap_idle),
    .ap_ready(grp_processImage_Pipeline_Filters_fu_479_ap_ready),
    .haar_counter(haar_counter_reg_450),
    .stage_sum(stage_sum_reg_438),
    .add_ln283(add_ln283_reg_1765),
    .zext_ln237(stddev_4_reg_415),
    .empty_13(trunc_ln201_reg_1540),
    .empty(trunc_ln260_3_reg_1587),
    .SUM1_data_address0(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address0),
    .SUM1_data_ce0(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce0),
    .SUM1_data_q0(SUM1_data_q0),
    .SUM1_data_address1(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address1),
    .SUM1_data_ce1(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce1),
    .SUM1_data_q1(SUM1_data_q1),
    .SUM1_data_address2(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address2),
    .SUM1_data_ce2(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce2),
    .SUM1_data_q2(SUM1_data_q2),
    .SUM1_data_address3(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address3),
    .SUM1_data_ce3(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce3),
    .SUM1_data_q3(SUM1_data_q3),
    .SUM1_data_address4(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address4),
    .SUM1_data_ce4(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce4),
    .SUM1_data_q4(SUM1_data_q4),
    .SUM1_data_address5(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address5),
    .SUM1_data_ce5(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce5),
    .SUM1_data_q5(SUM1_data_q5),
    .SUM1_data_address6(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address6),
    .SUM1_data_ce6(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce6),
    .SUM1_data_q6(SUM1_data_q6),
    .SUM1_data_address7(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address7),
    .SUM1_data_ce7(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce7),
    .SUM1_data_q7(SUM1_data_q7),
    .SUM1_data_address8(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address8),
    .SUM1_data_ce8(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce8),
    .SUM1_data_q8(SUM1_data_q8),
    .SUM1_data_address9(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address9),
    .SUM1_data_ce9(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce9),
    .SUM1_data_q9(SUM1_data_q9),
    .SUM1_data_address10(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address10),
    .SUM1_data_ce10(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce10),
    .SUM1_data_q10(SUM1_data_q10),
    .SUM1_data_address11(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address11),
    .SUM1_data_ce11(grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce11),
    .SUM1_data_q11(SUM1_data_q11),
    .stage_sum_1_out(grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out),
    .stage_sum_1_out_ap_vld(grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out_ap_vld)
);

detectFaces_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_540_p0),
    .ce(1'b1),
    .dout(grp_fu_540_p1)
);

detectFaces_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_590),
    .din1(64'd4600877379321698714),
    .ce(1'b1),
    .dout(grp_fu_555_p2)
);

detectFaces_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_590),
    .din1(mul277_i_reg_1778),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_560_p2)
);

detectFaces_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_564_p0),
    .ce(grp_fu_564_ce),
    .dout(grp_fu_564_p1)
);

detectFaces_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mean_reg_1680),
    .din1(mean_reg_1680),
    .ce(1'b1),
    .dout(grp_fu_567_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_int_sqrt_fu_474_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln268_reg_1702 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
            grp_int_sqrt_fu_474_ap_start_reg <= 1'b1;
        end else if ((grp_int_sqrt_fu_474_ap_ready == 1'b1)) begin
            grp_int_sqrt_fu_474_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_processImage_Pipeline_Filters_fu_479_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state36)) begin
            grp_processImage_Pipeline_Filters_fu_479_ap_start_reg <= 1'b1;
        end else if ((grp_processImage_Pipeline_Filters_fu_479_ap_ready == 1'b1)) begin
            grp_processImage_Pipeline_Filters_fu_479_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg <= 1'b1;
        end else if ((grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_ready == 1'b1)) begin
            grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln393_fu_608_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        AllCandidates_size_0_fu_210 <= AllCandidates_size_read;
    end else if (((icmp_ln282_reg_1711 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        AllCandidates_size_0_fu_210 <= add_ln218_fu_1427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln344_1_fu_1215_p2) & (1'b1 == ap_CS_fsm_state50))) begin
        haar_counter_reg_450 <= haar_counter_3_reg_1755;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        haar_counter_reg_450 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln344_1_fu_1215_p2) & (1'b1 == ap_CS_fsm_state50))) begin
        i_reg_427 <= add_ln282_reg_1715;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        i_reg_427 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln393_fu_608_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        pt_y_fu_206 <= 31'd0;
    end else if (((icmp_ln202_fu_865_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        pt_y_fu_206 <= add_ln201_reg_1529;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln344_1_fu_1215_p2) & (1'b1 == ap_CS_fsm_state50))) begin
        stage_sum_reg_438 <= grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        stage_sum_reg_438 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln268_reg_1702 == 1'd0) & (1'b1 == ap_CS_fsm_state31))) begin
        stddev_4_reg_415 <= 16'd1;
    end else if (((icmp_ln268_reg_1702 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        stddev_4_reg_415 <= stddev_3_reg_1706;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        x_reg_404 <= add_ln202_reg_1582;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        x_reg_404 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_190 <= 31'd0;
    end else if (((icmp_ln393_fu_608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_190 <= add_ln393_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        SQSUM1_data_load_2_reg_1670 <= SQSUM1_data_q1;
        SQSUM1_data_load_3_reg_1675 <= SQSUM1_data_q0;
        mean_reg_1680 <= mean_fu_944_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        SUM1_data_load_3_reg_1660 <= SUM1_data_q1;
        SUM1_data_load_4_reg_1665 <= SUM1_data_q0;
        sub_ln256_reg_1650 <= sub_ln256_fu_928_p2;
        sub_ln261_reg_1655 <= sub_ln261_fu_934_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add4_reg_1516 <= add4_fu_703_p2;
        add_ln409_reg_1492[16 : 6] <= add_ln409_fu_687_p2[16 : 6];
        add_reg_1511 <= add_fu_698_p2;
        trunc_ln400_2_reg_1487[16 : 6] <= trunc_ln400_2_fu_649_p1[16 : 6];
        y_1_reg_1479 <= y_fu_190;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln201_reg_1529 <= add_ln201_fu_730_p2;
        trunc_ln201_reg_1540 <= trunc_ln201_fu_770_p1;
        trunc_ln260_2_reg_1534[16 : 6] <= trunc_ln260_2_fu_766_p1[16 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln202_reg_1582 <= add_ln202_fu_870_p2;
        add_ln256_reg_1594 <= add_ln256_fu_880_p2;
        trunc_ln260_3_reg_1587 <= trunc_ln260_3_fu_876_p1;
        zext_ln202_reg_1574[30 : 0] <= zext_ln202_fu_861_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln262_1_reg_1561[16 : 6] <= add_ln262_1_fu_851_p2[16 : 6];
        data_1_reg_1567 <= data_1_fu_857_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        add_ln282_reg_1715 <= add_ln282_fu_995_p2;
        icmp_ln282_reg_1711 <= icmp_ln282_fu_989_p2;
        tmp_10_reg_1745 <= {{shl_ln18_1_fu_1088_p2[84:53]}};
        tmp_23_reg_1735 <= add_ln486_1_fu_1042_p2[32'd11];
        tmp_7_reg_1740 <= {{lshr_ln18_1_fu_1082_p2[84:53]}};
        xs_sign_1_reg_1730 <= data_1_reg_1567[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        add_ln283_reg_1765 <= add_ln283_fu_1128_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        cond_i57_reg_1556[63] <= cond_i57_fu_814_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        dc_reg_1827 <= grp_fu_387_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        haar_counter_3_reg_1755 <= haar_counter_3_fu_1118_p2;
        stages_array_load_reg_1750 <= stages_array_q0;
        stages_thresh_array_load_reg_1760 <= stages_thresh_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        icmp_ln268_reg_1702 <= icmp_ln268_fu_983_p2;
        trunc_ln237_reg_1697 <= trunc_ln237_fu_979_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        icmp_ln344_1_reg_1789 <= icmp_ln344_1_fu_1183_p2;
        icmp_ln344_2_reg_1794 <= icmp_ln344_2_fu_1189_p2;
        icmp_ln344_3_reg_1799 <= icmp_ln344_3_fu_1195_p2;
        icmp_ln344_reg_1784 <= icmp_ln344_fu_1177_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        icmp_ln61_1_reg_1817 <= icmp_ln61_1_fu_1263_p2;
        icmp_ln61_reg_1812 <= icmp_ln61_fu_1257_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        mul277_i_reg_1778 <= grp_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        mul_ln266_reg_1692 <= grp_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        notlhs_reg_1546 <= notlhs_fu_792_p2;
        notrhs_reg_1551 <= notrhs_fu_798_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_574 <= grp_fu_540_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state14))) begin
        reg_579 <= grp_fu_357_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_585 <= grp_fu_373_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state41))) begin
        reg_590 <= grp_fu_564_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        result_7_reg_1807 <= result_7_fu_1232_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        select_ln61_reg_1822[63] <= select_ln61_fu_1279_p3[63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        stddev_3_reg_1706 <= grp_int_sqrt_fu_474_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        stddev_reg_1686 <= stddev_fu_953_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        tmp_21_reg_1837 <= add_ln486_fu_1328_p2[32'd11];
        tmp_5_reg_1842 <= {{lshr_ln18_fu_1368_p2[84:53]}};
        tmp_6_reg_1847 <= {{shl_ln18_fu_1374_p2[84:53]}};
        xs_sign_reg_1832 <= data_fu_1287_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        zext_ln262_2_reg_1605[16 : 0] <= zext_ln262_2_fu_904_p1[16 : 0];
        zext_ln263_reg_1625[16 : 0] <= zext_ln263_fu_923_p1[16 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        AllCandidates_h_ce0_local = 1'b1;
    end else begin
        AllCandidates_h_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln282_reg_1711 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        AllCandidates_h_we0_local = 1'b1;
    end else begin
        AllCandidates_h_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        AllCandidates_w_ce0_local = 1'b1;
    end else begin
        AllCandidates_w_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln282_reg_1711 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        AllCandidates_w_we0_local = 1'b1;
    end else begin
        AllCandidates_w_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        AllCandidates_x_ce0_local = 1'b1;
    end else begin
        AllCandidates_x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln282_reg_1711 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        AllCandidates_x_we0_local = 1'b1;
    end else begin
        AllCandidates_x_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        AllCandidates_y_ce0_local = 1'b1;
    end else begin
        AllCandidates_y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln282_reg_1711 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        AllCandidates_y_we0_local = 1'b1;
    end else begin
        AllCandidates_y_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SQSUM1_data_address0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address0;
    end else begin
        SQSUM1_data_address0 = SQSUM1_data_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        SQSUM1_data_address0_local = zext_ln263_reg_1625;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        SQSUM1_data_address0_local = zext_ln261_fu_913_p1;
    end else begin
        SQSUM1_data_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SQSUM1_data_address1 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_address1;
    end else begin
        SQSUM1_data_address1 = SQSUM1_data_address1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        SQSUM1_data_address1_local = zext_ln262_2_reg_1605;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        SQSUM1_data_address1_local = zext_ln260_fu_894_p1;
    end else begin
        SQSUM1_data_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SQSUM1_data_ce0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce0;
    end else begin
        SQSUM1_data_ce0 = SQSUM1_data_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        SQSUM1_data_ce0_local = 1'b1;
    end else begin
        SQSUM1_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SQSUM1_data_ce1 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_ce1;
    end else begin
        SQSUM1_data_ce1 = SQSUM1_data_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        SQSUM1_data_ce1_local = 1'b1;
    end else begin
        SQSUM1_data_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SQSUM1_data_we0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SQSUM1_data_we0;
    end else begin
        SQSUM1_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_address0 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        SUM1_data_address0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address0;
    end else begin
        SUM1_data_address0 = zext_ln263_fu_923_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_address1 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        SUM1_data_address1 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_address1;
    end else begin
        SUM1_data_address1 = zext_ln262_2_fu_904_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_address2 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address2;
    end else begin
        SUM1_data_address2 = zext_ln261_fu_913_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_address3 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_address3;
    end else begin
        SUM1_data_address3 = zext_ln260_fu_894_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce0 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        SUM1_data_ce0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce0;
    end else begin
        SUM1_data_ce0 = SUM1_data_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        SUM1_data_ce0_local = 1'b1;
    end else begin
        SUM1_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce1 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        SUM1_data_ce1 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_ce1;
    end else begin
        SUM1_data_ce1 = SUM1_data_ce1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce10 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce10;
    end else begin
        SUM1_data_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce11 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce11;
    end else begin
        SUM1_data_ce11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        SUM1_data_ce1_local = 1'b1;
    end else begin
        SUM1_data_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce2 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce2;
    end else begin
        SUM1_data_ce2 = SUM1_data_ce2_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        SUM1_data_ce2_local = 1'b1;
    end else begin
        SUM1_data_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce3 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce3;
    end else begin
        SUM1_data_ce3 = SUM1_data_ce3_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        SUM1_data_ce3_local = 1'b1;
    end else begin
        SUM1_data_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce4 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce4;
    end else begin
        SUM1_data_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce5 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce5;
    end else begin
        SUM1_data_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce6 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce6;
    end else begin
        SUM1_data_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce7 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce7;
    end else begin
        SUM1_data_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce8 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce8;
    end else begin
        SUM1_data_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        SUM1_data_ce9 = grp_processImage_Pipeline_Filters_fu_479_SUM1_data_ce9;
    end else begin
        SUM1_data_ce9 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        SUM1_data_we0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_SUM1_data_we0;
    end else begin
        SUM1_data_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((grp_int_sqrt_fu_474_ap_done == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

always @ (*) begin
    if ((grp_processImage_Pipeline_Filters_fu_479_ap_done == 1'b0)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln201_fu_725_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln201_fu_725_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_fu_540_p0 = zext_ln202_reg_1574;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_540_p0 = zext_ln201_fu_720_p1;
    end else begin
        grp_fu_540_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        grp_fu_551_p1 = select_ln61_reg_1822;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_551_p1 = cond_i57_reg_1556;
    end else begin
        grp_fu_551_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | ((grp_processImage_Pipeline_Filters_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37)))) begin
        grp_fu_564_ce = 1'b1;
    end else begin
        grp_fu_564_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_564_p0 = grp_processImage_Pipeline_Filters_fu_479_stage_sum_1_out;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_564_p0 = sext_ln344_fu_1134_p1;
    end else begin
        grp_fu_564_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        stages_array_ce0_local = 1'b1;
    end else begin
        stages_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        stages_thresh_array_ce0_local = 1'b1;
    end else begin
        stages_thresh_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln393_fu_608_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln201_fu_725_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln202_fu_865_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((icmp_ln268_reg_1702 == 1'd0) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((grp_int_sqrt_fu_474_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((icmp_ln282_fu_989_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_processImage_Pipeline_Filters_fu_479_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((1'd1 == and_ln344_1_fu_1215_p2) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AllCandidates_h_address0 = zext_ln214_fu_1419_p1;

assign AllCandidates_h_ce0 = AllCandidates_h_ce0_local;

assign AllCandidates_h_d0 = winSize_width;

assign AllCandidates_h_we0 = AllCandidates_h_we0_local;

assign AllCandidates_w_address0 = zext_ln214_fu_1419_p1;

assign AllCandidates_w_ce0 = AllCandidates_w_ce0_local;

assign AllCandidates_w_d0 = winSize_width;

assign AllCandidates_w_we0 = AllCandidates_w_we0_local;

assign AllCandidates_x_address0 = zext_ln214_fu_1419_p1;

assign AllCandidates_x_ce0 = AllCandidates_x_ce0_local;

assign AllCandidates_x_d0 = result_fu_1411_p3;

assign AllCandidates_x_we0 = AllCandidates_x_we0_local;

assign AllCandidates_y_address0 = zext_ln214_fu_1419_p1;

assign AllCandidates_y_ce0 = AllCandidates_y_ce0_local;

assign AllCandidates_y_d0 = result_7_reg_1807;

assign AllCandidates_y_we0 = AllCandidates_y_we0_local;

assign IMG1_data_address0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_address0;

assign IMG1_data_ce0 = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_IMG1_data_ce0;

assign add4_fu_703_p2 = ($signed(sum_col) + $signed(32'd4294967272));

assign add_fu_698_p2 = ($signed(sum_row) + $signed(32'd4294967272));

assign add_ln201_fu_730_p2 = (pt_y_fu_206 + 31'd1);

assign add_ln202_fu_870_p2 = (x_reg_404 + 31'd1);

assign add_ln218_fu_1427_p2 = (AllCandidates_size_0_fu_210 + 32'd1);

assign add_ln256_fu_880_p2 = (trunc_ln260_3_fu_876_p1 + 17'd24);

assign add_ln260_1_fu_760_p2 = (p_shl2_fu_740_p3 + p_shl3_fu_752_p3);

assign add_ln260_fu_890_p2 = (trunc_ln260_2_reg_1534 + trunc_ln260_3_reg_1587);

assign add_ln261_fu_909_p2 = (trunc_ln260_2_reg_1534 + add_ln256_reg_1594);

assign add_ln262_1_fu_851_p2 = (zext_ln262_fu_835_p1 + zext_ln262_1_fu_847_p1);

assign add_ln262_fu_900_p2 = (add_ln262_1_reg_1561 + trunc_ln260_3_reg_1587);

assign add_ln263_fu_919_p2 = (add_ln262_1_reg_1561 + add_ln256_reg_1594);

assign add_ln282_fu_995_p2 = (i_reg_427 + 5'd1);

assign add_ln283_fu_1128_p2 = (stages_array_load_reg_1750 + empty_33_fu_1124_p1);

assign add_ln393_fu_613_p2 = (y_fu_190 + 31'd1);

assign add_ln400_fu_643_p2 = (p_shl_fu_623_p3 + p_shl1_fu_635_p3);

assign add_ln409_fu_687_p2 = (zext_ln409_fu_671_p1 + zext_ln409_1_fu_683_p1);

assign add_ln486_1_fu_1042_p2 = ($signed(zext_ln486_1_fu_1038_p1) + $signed(12'd3073));

assign add_ln486_fu_1328_p2 = ($signed(zext_ln486_fu_1324_p1) + $signed(12'd3073));

assign and_ln344_1_fu_1215_p2 = (grp_fu_560_p2 & and_ln344_fu_1209_p2);

assign and_ln344_fu_1209_p2 = (or_ln344_fu_1201_p2 & or_ln344_1_fu_1205_p2);

assign and_ln61_fu_1273_p2 = (or_ln61_fu_1269_p2 & grp_fu_376_p_dout0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_return = AllCandidates_size_0_fu_210;

assign bitcast_ln344_1_fu_1160_p1 = mul277_i_reg_1778;

assign bitcast_ln344_fu_1142_p1 = reg_590;

assign bitcast_ln61_fu_1239_p1 = reg_579;

assign cond_i57_fu_814_p3 = ((empty_32_fu_808_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign data_1_fu_857_p1 = grp_fu_387_p_dout0;

assign data_fu_1287_p1 = dc_reg_1827;

assign empty_29_fu_822_p2 = (trunc_ln201_reg_1540 + 8'd24);

assign empty_30_fu_788_p1 = value_assign_1_to_int_fu_774_p1[22:0];

assign empty_31_fu_804_p2 = (notrhs_reg_1551 | notlhs_reg_1546);

assign empty_32_fu_808_p2 = (grp_fu_376_p_dout0 & empty_31_fu_804_p2);

assign empty_33_fu_1124_p1 = haar_counter_reg_450[7:0];

assign empty_fu_657_p2 = ($signed(trunc_ln393_fu_653_p1) + $signed(8'd255));

assign grp_fu_357_p_ce = 1'b1;

assign grp_fu_357_p_din0 = reg_574;

assign grp_fu_357_p_din1 = factor;

assign grp_fu_373_p_ce = 1'b1;

assign grp_fu_373_p_din0 = reg_579;

assign grp_fu_376_p_ce = 1'b1;

assign grp_fu_376_p_din0 = reg_579;

assign grp_fu_376_p_din1 = 32'd0;

assign grp_fu_376_p_opcode = 5'd3;

assign grp_fu_387_p_ce = 1'b1;

assign grp_fu_387_p_din0 = reg_585;

assign grp_fu_387_p_din1 = grp_fu_551_p1;

assign grp_fu_387_p_opcode = 2'd0;

assign grp_int_sqrt_fu_474_ap_start = grp_int_sqrt_fu_474_ap_start_reg;

assign grp_processImage_Pipeline_Filters_fu_479_ap_start = grp_processImage_Pipeline_Filters_fu_479_ap_start_reg;

assign grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start = grp_processImage_Pipeline_VITIS_LOOP_398_2_fu_462_ap_start_reg;

assign haar_counter_3_fu_1118_p2 = (zext_ln283_fu_1114_p1 + haar_counter_reg_450);

assign icmp_ln201_fu_725_p2 = (($signed(zext_ln201_fu_720_p1) < $signed(add_reg_1511)) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_865_p2 = (($signed(zext_ln202_fu_861_p1) < $signed(add4_reg_1516)) ? 1'b1 : 1'b0);

assign icmp_ln268_fu_983_p2 = (($signed(stddev_2_fu_974_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_989_p2 = ((i_reg_427 < 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln344_1_fu_1183_p2 = ((trunc_ln344_fu_1156_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln344_2_fu_1189_p2 = ((tmp_9_fu_1163_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln344_3_fu_1195_p2 = ((trunc_ln344_1_fu_1173_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln344_fu_1177_p2 = ((tmp_8_fu_1146_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln393_fu_608_p2 = (($signed(zext_ln393_fu_604_p1) < $signed(sum_row)) ? 1'b1 : 1'b0);

assign icmp_ln61_1_fu_1263_p2 = ((trunc_ln61_fu_1253_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_1257_p2 = ((tmp_3_fu_1243_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln18_1_fu_1082_p2 = zext_ln15_1_fu_1034_p1 >> zext_ln18_1_fu_1078_p1;

assign lshr_ln18_fu_1368_p2 = zext_ln15_fu_1320_p1 >> zext_ln18_fu_1364_p1;

assign mantissa_1_fu_1024_p4 = {{{{1'd1}, {trunc_ln505_1_fu_1021_p1}}}, {1'd0}};

assign mantissa_fu_1310_p4 = {{{{1'd1}, {trunc_ln505_fu_1306_p1}}}, {1'd0}};

assign mean_fu_944_p2 = (SUM1_data_load_4_reg_1665 + sub_ln262_fu_940_p2);

assign notlhs_fu_792_p2 = ((tmp_1_fu_778_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_798_p2 = ((empty_30_fu_788_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_ln344_1_fu_1205_p2 = (icmp_ln344_3_reg_1799 | icmp_ln344_2_reg_1794);

assign or_ln344_fu_1201_p2 = (icmp_ln344_reg_1784 | icmp_ln344_1_reg_1789);

assign or_ln61_fu_1269_p2 = (icmp_ln61_reg_1812 | icmp_ln61_1_reg_1817);

assign p_shl1_fu_635_p3 = {{trunc_ln400_1_fu_631_p1}, {6'd0}};

assign p_shl2_fu_740_p3 = {{trunc_ln260_fu_736_p1}, {8'd0}};

assign p_shl3_fu_752_p3 = {{trunc_ln260_1_fu_748_p1}, {6'd0}};

assign p_shl_fu_623_p3 = {{trunc_ln400_fu_619_p1}, {8'd0}};

assign result_2_fu_1405_p2 = (32'd0 - val_fu_1400_p3);

assign result_6_fu_1226_p2 = (32'd0 - val_1_fu_1221_p3);

assign result_7_fu_1232_p3 = ((xs_sign_1_reg_1730[0:0] == 1'b1) ? result_6_fu_1226_p2 : val_1_fu_1221_p3);

assign result_fu_1411_p3 = ((xs_sign_reg_1832[0:0] == 1'b1) ? result_2_fu_1405_p2 : val_fu_1400_p3);

assign select_ln18_2_fu_1066_p3 = ((tmp_23_fu_1048_p3[0:0] == 1'b1) ? sext_ln18_2_fu_1062_p1 : add_ln486_1_fu_1042_p2);

assign select_ln18_fu_1352_p3 = ((tmp_21_fu_1334_p3[0:0] == 1'b1) ? sext_ln18_fu_1348_p1 : add_ln486_fu_1328_p2);

assign select_ln61_fu_1279_p3 = ((and_ln61_fu_1273_p2[0:0] == 1'b1) ? 64'd4602678819172646912 : 64'd13826050856027422720);

assign sext_ln18_1_fu_1360_p1 = $signed(select_ln18_fu_1352_p3);

assign sext_ln18_2_fu_1062_p1 = $signed(sub_ln18_1_fu_1056_p2);

assign sext_ln18_3_fu_1074_p1 = $signed(select_ln18_2_fu_1066_p3);

assign sext_ln18_fu_1348_p1 = $signed(sub_ln18_fu_1342_p2);

assign sext_ln344_fu_1134_p1 = $signed(stages_thresh_array_load_reg_1760);

assign shl_ln18_1_fu_1088_p2 = zext_ln15_1_fu_1034_p1 << zext_ln18_1_fu_1078_p1;

assign shl_ln18_fu_1374_p2 = zext_ln15_fu_1320_p1 << zext_ln18_fu_1364_p1;

assign shl_ln265_1_fu_963_p2 = stddev_reg_1686 << 32'd6;

assign shl_ln265_fu_958_p2 = stddev_reg_1686 << 32'd9;

assign stages_array_address0 = zext_ln282_fu_1001_p1;

assign stages_thresh_array_address0 = zext_ln282_fu_1001_p1;

assign stddev_1_fu_968_p2 = (shl_ln265_fu_958_p2 + shl_ln265_1_fu_963_p2);

assign stddev_2_fu_974_p2 = (stddev_1_fu_968_p2 - mul_ln266_reg_1692);

assign stddev_fu_953_p2 = (SQSUM1_data_load_3_reg_1675 + sub_ln257_fu_949_p2);

assign sub_ln18_1_fu_1056_p2 = (11'd1023 - xs_exp_1_fu_1014_p3);

assign sub_ln18_fu_1342_p2 = (11'd1023 - xs_exp_fu_1298_p3);

assign sub_ln256_fu_928_p2 = (SQSUM1_data_q1 - SQSUM1_data_q0);

assign sub_ln257_fu_949_p2 = (sub_ln256_reg_1650 - SQSUM1_data_load_2_reg_1670);

assign sub_ln261_fu_934_p2 = (SUM1_data_q3 - SUM1_data_q2);

assign sub_ln262_fu_940_p2 = (sub_ln261_reg_1655 - SUM1_data_load_3_reg_1660);

assign tmp_17_fu_675_p3 = {{empty_fu_657_p2}, {6'd0}};

assign tmp_18_fu_827_p3 = {{empty_29_fu_822_p2}, {8'd0}};

assign tmp_19_fu_839_p3 = {{empty_29_fu_822_p2}, {6'd0}};

assign tmp_1_fu_778_p4 = {{value_assign_1_to_int_fu_774_p1[30:23]}};

assign tmp_21_fu_1334_p3 = add_ln486_fu_1328_p2[32'd11];

assign tmp_23_fu_1048_p3 = add_ln486_1_fu_1042_p2[32'd11];

assign tmp_3_fu_1243_p4 = {{bitcast_ln61_fu_1239_p1[30:23]}};

assign tmp_8_fu_1146_p4 = {{bitcast_ln344_fu_1142_p1[62:52]}};

assign tmp_9_fu_1163_p4 = {{bitcast_ln344_1_fu_1160_p1[62:52]}};

assign tmp_fu_663_p3 = {{empty_fu_657_p2}, {8'd0}};

assign trunc_ln201_fu_770_p1 = pt_y_fu_206[7:0];

assign trunc_ln237_fu_979_p1 = stddev_2_fu_974_p2[30:0];

assign trunc_ln260_1_fu_748_p1 = pt_y_fu_206[28:0];

assign trunc_ln260_2_fu_766_p1 = add_ln260_1_fu_760_p2[16:0];

assign trunc_ln260_3_fu_876_p1 = x_reg_404[16:0];

assign trunc_ln260_fu_736_p1 = pt_y_fu_206[26:0];

assign trunc_ln344_1_fu_1173_p1 = bitcast_ln344_1_fu_1160_p1[51:0];

assign trunc_ln344_fu_1156_p1 = bitcast_ln344_fu_1142_p1[51:0];

assign trunc_ln393_fu_653_p1 = y_fu_190[7:0];

assign trunc_ln400_1_fu_631_p1 = y_fu_190[28:0];

assign trunc_ln400_2_fu_649_p1 = add_ln400_fu_643_p2[16:0];

assign trunc_ln400_fu_619_p1 = y_fu_190[26:0];

assign trunc_ln505_1_fu_1021_p1 = data_1_reg_1567[51:0];

assign trunc_ln505_fu_1306_p1 = data_fu_1287_p1[51:0];

assign trunc_ln61_fu_1253_p1 = bitcast_ln61_fu_1239_p1[22:0];

assign val_1_fu_1221_p3 = ((tmp_23_reg_1735[0:0] == 1'b1) ? tmp_7_reg_1740 : tmp_10_reg_1745);

assign val_fu_1400_p3 = ((tmp_21_reg_1837[0:0] == 1'b1) ? tmp_5_reg_1842 : tmp_6_reg_1847);

assign value_assign_1_to_int_fu_774_p1 = reg_579;

assign xs_exp_1_fu_1014_p3 = {{data_1_reg_1567[62:52]}};

assign xs_exp_fu_1298_p3 = {{data_fu_1287_p1[62:52]}};

assign zext_ln15_1_fu_1034_p1 = mantissa_1_fu_1024_p4;

assign zext_ln15_fu_1320_p1 = mantissa_fu_1310_p4;

assign zext_ln18_1_fu_1078_p1 = $unsigned(sext_ln18_3_fu_1074_p1);

assign zext_ln18_fu_1364_p1 = $unsigned(sext_ln18_1_fu_1360_p1);

assign zext_ln201_fu_720_p1 = pt_y_fu_206;

assign zext_ln202_fu_861_p1 = x_reg_404;

assign zext_ln214_fu_1419_p1 = AllCandidates_size_0_fu_210;

assign zext_ln260_fu_894_p1 = add_ln260_fu_890_p2;

assign zext_ln261_fu_913_p1 = add_ln261_fu_909_p2;

assign zext_ln262_1_fu_847_p1 = tmp_19_fu_839_p3;

assign zext_ln262_2_fu_904_p1 = add_ln262_fu_900_p2;

assign zext_ln262_fu_835_p1 = tmp_18_fu_827_p3;

assign zext_ln263_fu_923_p1 = add_ln263_fu_919_p2;

assign zext_ln282_fu_1001_p1 = i_reg_427;

assign zext_ln283_fu_1114_p1 = stages_array_q0;

assign zext_ln393_fu_604_p1 = y_fu_190;

assign zext_ln409_1_fu_683_p1 = tmp_17_fu_675_p3;

assign zext_ln409_fu_671_p1 = tmp_fu_663_p3;

assign zext_ln486_1_fu_1038_p1 = xs_exp_1_fu_1014_p3;

assign zext_ln486_fu_1324_p1 = xs_exp_fu_1298_p3;

always @ (posedge ap_clk) begin
    trunc_ln400_2_reg_1487[5:0] <= 6'b000000;
    add_ln409_reg_1492[5:0] <= 6'b000000;
    trunc_ln260_2_reg_1534[5:0] <= 6'b000000;
    cond_i57_reg_1556[62:0] <= 63'b011111111100000000000000000000000000000000000000000000000000000;
    add_ln262_1_reg_1561[5:0] <= 6'b000000;
    zext_ln202_reg_1574[31] <= 1'b0;
    zext_ln262_2_reg_1605[63:17] <= 47'b00000000000000000000000000000000000000000000000;
    zext_ln263_reg_1625[63:17] <= 47'b00000000000000000000000000000000000000000000000;
    select_ln61_reg_1822[62:0] <= 63'b011111111100000000000000000000000000000000000000000000000000000;
end

endmodule //detectFaces_processImage
